### ISSUE TITLE
Switch Grid and TreeGrid to extend AbstractGrid

### ISSUE THREAD

**Issue by pleku** [vaadin/vaadin-grid-flow#1005]
This would be done together with the introducing DataView API since it is targeted to `Grid` but not to `TreeGrid` as the hierarchical data structure needs some extra considerations.

The idea is to 
- rename current `Grid` to `AbstractGrid` and then add a new `Grid extends AbstractGrid` which introduces the data view APIs that don't apply for `TreeGrid`
- if there is any existing API in grid that should not be in `TreeGrid` but have been inherited there, those could be deprecated for later removal and duplicated in the new `Grid`
- any future `Grid` API can be introduced without having to consider `TreeGrid` immediately and `TreeGrid` will not be bloated with API that doesn't make sense

This would not be a backwards compatible for any code that tries to cast/change type of `TreeGrid` into `Grid`, those would have to be migrated to cast to `AbstractGrid` instead of `Grid`. This is relatively small change though and the idea would not be to make this change directly in 14 LTS but first gather feedback from users in at least 17.

**Comment by caalador** [comment]
This is not doable without significant changes as the interface generics will not be compatible with the extending class and arguments cannot be inferred.
This can already now be noted in the case where you have TreeGrid an would want to use it as is to add a selection listener for instance as:
```

        TreeGrid<String> grid = new TreeGrid<>();

        GridMultiSelectionModel<String> model = (GridMultiSelectionModel<String>) grid
                .setSelectionMode(SelectionMode.MULTI);

        AtomicReference<MultiSelectionEvent<TreeGrid<String>, String>> event = new AtomicReference<>();
        MultiSelectionListener<TreeGrid<String>, String> selectionListener = evt -> {
            assertNull(event.get());
            event.set(evt);
        };
        model.addMultiSelectionListener(selectionListener);
```
This will already fail with the exception
```
Required type:   MultiSelectionListener<Grid<String>, String>
Provided:           MultiSelectionListener<TreeGrid<String>, String>
```
And making Grid abstract would make this a problem also for `Grid<T> extends AbstractGrid<T>`
