### ISSUE TITLE
When should I set GridDropMode

### ISSUE THREAD

**Issue by vcvuwac** [vaadin/vaadin-grid-flow#1008]
`GridDropMode` is set in a DragStartListener and is removed in a DragEndListener in [this example](https://vaadin.com/components/vaadin-grid/java-examples/drag-and-drop). What does this mean? 
There was no problem when I set it outside a listener and didn't remove it.

**Comment by tomivirkki** [comment]
It's not necessary to toggle on and off, but it's recommended in case you want to prevent unintentional drag-over effects while dragging text or rows of another grid on the page etc.

For instance, in the grid examples you linked, we want to avoid showing the visual drop indicators on the "Drag Rows Between Grids" demo's grid, when you're dragging a row from the "Row Reordering" demo over it.

**Comment by vcvuwac** [comment]
@tomivirkki 
Thank you for your answer. I understood it's very dangerous.
I was able to drop **text** on a grid, and `draggedItem`, a field to store a dragged row, was null when drop listener was running.
I think you should warn users of this problem in the above example or in the [docs](https://vaadin.com/docs/v14/flow/dnd/generic-dnd.html) because most people don't make test cases like "Select text, and drop it on a grid".
