### ISSUE TITLE
Grid "4.1.0" is not OSGi compatible

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/vaadin-grid-flow#1030]
Grid has a dependency to `DndUtil` class in `flow-dnd`  module which is in the package `com.vaadin.flow.component.dnd.internal`.
This package is not exposed in OSGi bundle so grid _may no use it_.
Currently `vaadin-grid-flow` bundle is broken because it's not possible to resolve `com.vaadin.flow.component.dnd.internal` dependency.
As a result : all `14.2`  platform is not OSGi compatible.

Grid affects `vaadin-grid-pro-flow` and `vaadin-crud-flow`.
So three modules in Platform are not OSGi compatible.

**Comment by pleku** [comment]
We've fixed this issue already once: https://github.com/vaadin/vaadin-grid-flow/pull/863
But it seems we have not picked it to grid versions for Vaadin 14 `4.1` & `4.2` which should be done.

**Comment by denis-anisimov** [comment]
This is already fixed in grid-flow `4.1.4` which is part of `14.2.1`  Platform.
