### ISSUE TITLE
scrollTo methods in Grid cause render bugs

### ISSUE THREAD

**Issue by sirbris** [vaadin/vaadin-grid-flow#1048]
Vaadin 14.2.1:
When adding items to a Grid and programatically scrolling to the end, empty rows appear at the top after 3rd time.
Small test case scenario to reproduce the issue... press button at least three times.

```
        List<String> items = new ArrayList<>();
        Grid<String> grid = new Grid<>();
        grid.setItems(items);
        grid.addColumn(item -> item);

        Button btn = new Button("Add item");
        btn.addClickListener(event -> {
            items.add("New item " + System.currentTimeMillis());
            grid.getDataProvider().refreshAll();
            grid.scrollToEnd();
        });

        add(grid, btn);
```

**Comment by TatuLund** [comment]
Can you check the workaround mentioned here https://github.com/vaadin/vaadin-grid-flow/issues/944

**Comment by TatuLund** [comment]
See also https://github.com/vaadin/vaadin-grid-flow/issues/1028

**Comment by TatuLund** [comment]
See also https://github.com/vaadin/vaadin-grid-flow/issues/882

**Comment by sirbris** [comment]
> Can you check the workaround mentioned here #944

Yes, that workaround worked

**Comment by AB-xdev** [comment]
Sometimes we experience similar problem with ``scrollToIndex`` in a TreeGrid:
![grafik](https://user-images.githubusercontent.com/45384811/92470436-b3cbe180-f1d6-11ea-8dd3-46fd0cac6fb7.png)

Is it possible that the underlying issue is the same?
