### ISSUE TITLE
Adding a tree grid from client side and another grid from server side causes javascript error

### ISSUE THREAD

**Issue by timbo86** [vaadin/vaadin-grid-flow#1077]
When we add a tree grid for navigation purpose in our layout js module and then afterwards add another grid from java on the same view, we get following error:
_Cannot read property 'beforeEnsureSubCacheForScaledIndex' of undefined_
Also the tree grid will immediately collapse and not expand anymore, but the toggle icons will change correctly.

Adding both grids from only client or server side works. But in our case we would definitely need the mixed variant.

It can be easily reproduced by adding a js module with a tree grid and a slot for other components inside and creating related java class with an add method, in order to add elements to that slot. When the view is attached, just add another grid to that slot and also provide data.

**Comment by DiegoCardoso** [comment]
Hi @timbo86,

I am checking this issue and after following your instructions, I couldn't reproduce it. Maybe something is missing on my side, so would you mind to attach a small project reproducing the issue?

Thanks in advance

**Comment by eforest** [comment]
Hi,
here’s a demo project to reproduce the problem. 
It contains two routes:
•	/working: shows tree grid that can be expanded
•	/not-working: now tree grid can’t be expanded any more

[tree-grid-demo.zip](https://github.com/vaadin/vaadin-grid-flow/files/5122165/tree-grid-demo.zip)

**Comment by DiegoCardoso** [comment]
Hi,

Thanks for the example. Now I could confirm it and see somehow where it's coming from.

**Comment by DiegoCardoso** [comment]
Reopening after a regression was found caused after a second server grid is attached.
