### ISSUE TITLE
Missing API for selecting multiple items

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/vaadin-grid-flow#115]
Consider extending the signature of `select(item)` to `select(items...)` so that several items can be selected when using multi-select mode.

**Comment by pleku** [comment]
This is already considered as a part of https://github.com/vaadin/vaadin-grid-flow/issues/73

**Comment by pleku** [comment]
Actually no, this is still valid and not directly related to #73 but would be good to do after (or as a part of) that one.

**Comment by pleku** [comment]
Effectively, the API should be as close to same as in V8: https://github.com/vaadin/framework/blob/master/server/src/main/java/com/vaadin/ui/MultiSelect.java
