### ISSUE TITLE
Broken dependency to vaadin-checkbox in beta3

### ISSUE THREAD

**Issue by johndevs** [vaadin/vaadin-grid-flow#116]
Currently com.vaadin:vaadin-grid-flow:1.0.0.beta3 POM refers to vaadin-checkbox-2.0.0-beta1.jar which does not exist in https://mvnrepository.com/artifact/org.webjars.bowergithub.vaadin/vaadin-checkbox nor in https://maven.vaadin.com/vaadin-prereleases/org/webjars/bowergithub/vaadin/vaadin-checkbox. This breaks the BOM and subsequently the build.

**Comment by gilberto-torrezan** [comment]
Fixed by https://github.com/webjars/webjars/issues/1734

**Comment by johndevs** [comment]
Thanks @gilberto-torrezan !
