### ISSUE TITLE
It's not possible to create a ColumnGroup with just one column via public API

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/vaadin-grid-flow#120]
Related to the issue https://github.com/vaadin/vaadin-grid-flow/issues/59

Currently it's not possible to create a ColumnGroup with just one column via public API. The `mergeColumns` methods don't accept a single column as parameter (and the method name for this use case feels strange anyway).

Groups with one single column are important to provide ways of adding different "rows" of headers for the same column. For instance, when adding a filtering text field below the header text.

**Comment by pekam** [comment]
Fixed in #163
