### ISSUE TITLE
SPIKE: recreate basic features demo from V8 Grid

### ISSUE THREAD

**Issue by pleku** [vaadin/vaadin-grid-flow#129]
Recreate the example https://demo.vaadin.com/sampler/#ui/grids-and-trees/grid/features and do an analysis on what is difficult and how it could be improved on. One particular topic is building the header rows for grouping and adding components for filtering.

This will (hopefully) provide some insight on how to improve for #120 and #59.

### Acceptance Criteria
- The demo is available for vcom
- There has been a design meeting for improving the API

**Comment by ZheSun88** [comment]
ATM there is one branch https://github.com/vaadin/vaadin-grid-flow/tree/spike/129 with basic features ( without Filter feature) which are similar to the one used in the sampler demo.
