### ISSUE TITLE
Clicking on a row with details does not open the row in IE11

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-grid-flow#136]
See https://github.com/vaadin/vaadin-components-testbench/blob/master/vaadin-components-testbench-test/src/main/java/com/vaadin/flow/component/grid/testbench/test/GridView.java#L105

Clicking on a row in the test opens the details in all other browsers but not in  IE11

**Comment by caalador** [comment]
IE11 receives a `'Symbol' is undefined` in a for iterator that is in the connector as `for (let page of pagesToUpdate) {` and is then expanded to 
```
for(var _iterator = pagesToUpdate[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {
    var page = _step.value;
```
