### ISSUE TITLE
Make it possible to align columns

### ISSUE THREAD

**Issue by Legioth** [vaadin/vaadin-grid-flow#146]
There's currently no easy way of aligning cell contents for a column. Today, you'd have to create a template renderer to be able to add a wrapping element around the actual cell contents to be able to target the contents with styling.

Should check whether there's any easy way of targeting all cells of a specific column in `<vaadin-grid>`, and either use that feature or create a ticket for that project if it's not possible.

**Comment by Legioth** [comment]
After some discussion with @tomivirkki, it seems like there are three options:
1) Add a feature only to `Grid` that wraps the renderer's template contents with an element managed by the `Column`. The benefit of this is that it doesn't require any changes to the Web Component, but the drawback is that it increases the number of elements in the DOM by one per cell.
2) Add a feature to `<vaadin-grid>` that would add `class` values or arbitrary attributes to the `<vaadin-grid-cell-content>` element in the component's light DOM. The benefit of this is that it's really easy to target that element with styles, but the drawback is that the existence of those elements are kind-of implementation details and it might not be desirable to expose them in that way.
3) Add a feature to `<vaadin-grid>` that would add `class` values or arbitrary attributes to the `<td>` elements inside the component's shadow root. The benefit here is that this wouldn't expose any implementation details of the component, but the drawback is that it requires styles to be injected into its shadow root. Another benefit is that this this would be the only reasonable solution if we would ever implement something similar to `rowStyleGenerator` from V8 since only the internal `<tr>` elements are actually covering the entire row.

**Comment by pleku** [comment]
Missing this feature from 10 is a shame, but we should probably show a nice way to workaround it - eg. add/modify a demo that introduces an extra element in the cell that applies the alignment.

**Comment by pleku** [comment]
Since 5.2.0.beta1, we can now use the `text-align` property for the columns 
https://cdn.vaadin.com/vaadin-grid/5.2.0-beta1/#/elements/vaadin-grid-column#property-textAlign

**Comment by sirbris** [comment]
Does not seem to work when using ComponentRenderer... what would be a good workaround to center Icons in a grid column?
