### ISSUE TITLE
Grid doesn't show up in IE11 as height is missing from the VerticalLayout

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/vaadin-grid-flow#158]
## step to reproduce
1. take `master` from `BeverageBuddy`
2. run `mvn jetty:run -Dvaadin.productionMode`
3. navigate to `http://localhost:8080/categories`

## Expected behavior
Grid can be shown properly

## Actual behavior
![image](https://user-images.githubusercontent.com/31067185/38976054-b18f5ace-43b8-11e8-94aa-db39a5501606.png)

## Versions
OS: windows 10
IE: 11.371.16299.0
Vaadin platform: beta8
flow: beta7
flow-maven-plugin: beta7

## Quick Check
add `height` to the `vaadin-vertical-layout` can let the grid show up

**Comment by gilberto-torrezan** [comment]
Please also check whether the body has a defined size or not. The Layouts don't behave properly when the body size is undefined.

**Comment by ZheSun88** [comment]
Shouldn't the Body Size be defined by default with the latest flow?

**Comment by gilberto-torrezan** [comment]
Yes, it should, so please check if it is really being applied or not.

**Comment by ZheSun88** [comment]
computed style from `body` Element
![image](https://user-images.githubusercontent.com/31067185/38977550-5bb91c2a-43bd-11e8-834e-791533e754f6.png)

**Comment by caalador** [comment]
Works as expected in Windows8.1 + IE11
I'm wondering how critical is it to have Windows10 + IE11 as it's not the default browser there and needs special steps to use.

**Comment by gilberto-torrezan** [comment]
@caalador so it only breaks on Windows 10 now? That's strange.

**Comment by ZheSun88** [comment]
it doesn't happen with Windows 10 now. tested with  beverage-starter with snapshot version before flow beta9 are published.

**Comment by gilberto-torrezan** [comment]
If this particular issue is fixed, then it's fixed. A new ticket can be opened for other layout issues.
