### ISSUE TITLE
Grid crashes with a client-side error when using a backend DataProvider with more items than the page size

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/vaadin-grid-flow#171]
Here is a small code snippet that shows the problem:

```java
List<String> items = new ArrayList<>();
for (int i = 0; i < 51; i++) {
    items.add(String.valueOf(i));
}

DataProvider<String, Void> dataProvider = DataProvider
    .fromCallbacks(query -> {
        return items.stream();
    }, query -> {
        return items.size();
});

Grid<String> grid = new Grid<String>();
grid.setDataProvider(dataProvider);
grid.addColumn(ValueProvider.identity());
```

The error is:

```
Cannot read property 'length' of undefined
```

When using 50 items instead of 51, the error doesn't happen. Also, the error doesn't happen when using a `ListDataProvider`.

![vaadin-grid-error](https://user-images.githubusercontent.com/7464735/39303719-ec23c128-495f-11e8-83b5-73a9d0dd6b26.png)

This bug was first submitted in this forum thread: https://vaadin.com/forum/thread/17059290

**Comment by Legioth** [comment]
I suspect your data provider is broken: it returns more items than asked for.

**Comment by Legioth** [comment]
Also, it returns a stream starting with the first item even if it would be asked to return a stream starting with item n.

So in summary, the problem is because the implementation doesn't take `query.getOffset()` and `query.getLimit()` into account.

**Comment by Artur-** [comment]
That is no reason for a client side exception

**Comment by Legioth** [comment]
True. We should deal with this in a more graceful way. As a first step, I would suggest checking for these three scenarios, and throw with a descriptive error message:
* Returned `Stream` is longer than expected
* `Query.getLimit()` has not been called from inside the fetch method
* `Query.getOffset()` has not been called from inside the fetch method
