### ISSUE TITLE
Grid Component Renderers not working when navigated to using RouterLayout

### ISSUE THREAD

**Issue by davidm76** [vaadin/vaadin-grid-flow#180]
When using a RouterLayout to naviaged between two grids, Component Renders using in the grid do not work until the browser is manually refreshed.
The following repo has a project which demonstrates the issue:
[https://github.com/davidm76/comp_renderer_issue]()

The ruling project and the issue is shown in the GIF below:
![component_renderer_issue](https://user-images.githubusercontent.com/6536626/39618344-35903a96-4f7b-11e8-8fb0-a3cd8f2ac631.gif)

Thanks.

Ps, Flow is looking great.

**Comment by ZheSun88** [comment]
Hi David,

Can i ask you to test again with platform version `10.0.0.beta9`? ( you will also need to update the `flow-spring-boot-starter` dependency to `vaadin-spring-boot-starter` ) locally i cannot reproduce this error with the new version

**Comment by davidm76** [comment]
Thank you very much.  That's sorted it.
