### ISSUE TITLE
setColumns(String...) method missing

### ISSUE THREAD

**Issue by mstahv** [vaadin/vaadin-grid-flow#184]
The handy helper method from V8 is missing from Flow version. "bean grid" functionality isn't really handy without this.

**Comment by Legioth** [comment]
There is a small risk that it won't work to update the column ordering after the component has been initially rendered. In that case, we could add a `Grid(Class<T> beanType, String ... columns)` constructor instead since that would leave out the possibility of reordering the columns later on.

**Comment by mstahv** [comment]
This needs to be fixed properly soon anyways so why not add the feature to the web component as well. For DX a method would be better too, even if it initially had limitations (only works for initial rendering).

**Comment by Legioth** [comment]
> For DX a method would be better too, even if it initially had limitations (only works for initial rendering).

In what way is it better for DX to have a method that you can call, but it doesn't have the intended effect?

**Comment by mstahv** [comment]
People look for the method. Both because they have used to and usually this kind of things are configured. There might even be separate method to do column configuration (reading it from user settings) and instantiation of the Grid has then already happened.

**Comment by mstahv** [comment]
With most components, I first create them and then start to look for (using IDEs autocompletion) how can I configure it.
