### ISSUE TITLE
Add StyleGenerator to Grid as in V8

### ISSUE THREAD

**Issue by Legioth** [vaadin/vaadin-grid-flow#185]
@stefanuebe commented on [Mon May 07 2018](https://github.com/vaadin/flow/issues/4074)

I have a grid of calendar weeks and persons where I want to mark the current calendar week through css styles for a better recognition. Currently this is not possible (templates are not a suitable solution).

The request is to extend the `Grid` / `Column` API with some kind of "StyleGenerator" methods as in V8. This API should make it possible to:

1. set class names for a column (like `HasStyle` for `Column`) 
2. set class names for the rows based on a item (like `Grid.setStyleGenerator`  in V8)
3. set class names for single cells (like `Grid.Column.setStyleGenerator` in V8) 

Since all these method produce css class names, they should be usable in combination without problems. To have same names we could name it e.g. `ClassNameGenerator` instead of `StyleGenerator`

Usage examples for my use case
1. mark the current week in a timeline grid: `grid.addColumn("...").addClassName("current-week");`
2. mark persons, that are finished with their project work: `grid.setStyleGenerator(person -> person.isFinished() ? "finished" : null);`
3. mark persons, that are absent for a specific week `grid.addColumn("...").setStyleGenerator(item -> person.isAbsent() ? "absent" : null);`

**Comment by Legioth** [comment]
Slightly related to https://github.com/vaadin/vaadin-grid-flow/issues/146

**Comment by gilberto-torrezan** [comment]
For row styles, there's no support yet on the webcomponent to set them. See https://github.com/vaadin/vaadin-grid/issues/1311 for details.

**Comment by Legioth** [comment]
Why not add cell style support now, and then split out row styles to a separate ticket that can be fixed once the web component feature is added?

**Comment by AdamBrowning** [comment]
This would be a very welcome addition as @Legioth said even just the cell styling would be a vast quality of life improvement.

**Comment by gilberto-torrezan** [comment]
To support style generators or `addClassNames` to the cells, while using `TemplateRenderers`, we would need to encapsulate the contents of the cell in an element, and set the classes or styles to that element.

Example: in a `TemplateRenderer` like this:

```
grid.addColumn(TemplateRenderer.of("[[item.value]]")).setStyleGenerator(item -> person.isAbsent() ? "absent" : null);
```

The end result on the client side would be something like this:

```
<vaadin-grid-cell-content>
    <span class="absent">[[item.value]]</span>
</vaadin-grid-cell-content>
```

Which is fine, but it can break some layouts depending on how complex is the template.

Also `ComponentRenderer`s would need to be wrapped as well.

**Comment by Legioth** [comment]
We wouldn't break any existing layouts if an additional wrapping element would only be used in cases when a style generator has actually been configured for the column.

For `ComponentRenderer`, we wouldn't even have to add any wrapping element since the root of a component is already only one element. On the other hand, for the component case you can just as well apply styling in the callback where you create and configure the component.

**Comment by web-padawan** [comment]
Depends on vaadin/vaadin-grid#1297

**Comment by kolle1986** [comment]
Is this available through grid java api in Vaadin flow?
