### ISSUE TITLE
need docs to explain how to theme components inside grid

### ISSUE THREAD

**Issue by bennewi** [vaadin/vaadin-grid-flow#189]
I was able to add TextFields to a grid but I got confused how to style them. After referring to [themable mixin wiki](https://github.com/vaadin/vaadin-themable-mixin/wiki/4.-Scoping-Styles-in-a-Theme-Module) I was able to solve it. Scenarios:

1) Changing the padding to make the grid more compact
2) Changing the background color of certain fields to indicate status
3) Change border of certain fields to indicate additional status
4) Changing the horiz align of the text in the TextFields to centered

This involved me specifying:
`[part="value"]`
`[part="input-field"]` and 
`[part="input-field"]::after`

in the `theme-for="vaadin-text-field"`

It would be helpful to provide some hints in the core documentation for making these

**Comment by pleku** [comment]
We should have an example on how to theme Vaadin components inside `Grid` or `IronList`.
