### ISSUE TITLE
ItemClickListener and ItemDoubleClickListener for Grid

### ISSUE THREAD

**Issue by esommars** [vaadin/vaadin-grid-flow#195]

**Comment by esommars** [comment]
When in multiselect mode one wants to be able to select many rows by checking the checkbox and do operations like copy,delete ,etc on those rows. When clicking on the rest of the row that would perform a different action opening the details for example.

**Comment by F43nd1r** [comment]
This is currently blocking my migration to vaadin 10 (https://github.com/F43nd1r/Acrarium/pull/13). Is there any workaround or schedule for this feature?

**Comment by pleku** [comment]
The name of the event should be `ItemClickEvent`. It should have the following data:
- Mouse event details, same as in https://vaadin.com/api/platform/11.0.1/com/vaadin/flow/component/ClickEvent.html
- The bean / item of the row that was clicked
- NO clicked column, for now (this can be achieved with component/template renderers for that column)
- The specific API for `TreeGrid` will be added in another issue

### Acceptance Criteria
- There is a demo highlighting this feature

**Comment by gilberto-torrezan** [comment]
On the webcomponent there's a private function that takes care of client events and do the proper activation of items (that can lead to selection and so on).

[Here is the code](https://github.com/vaadin/vaadin-grid/blob/25b6a8447b53f69491fc45acb567b11e9ed4c8ed/src/vaadin-grid-active-item-mixin.html#L49). The Grid connector could override that function or use similar approach to get the client event (with the button used, numbers of clicks and so on), the clicked row number and the clicked item.

**Comment by Legioth** [comment]
Instead of overriding (yet another) private method, it would be preferable if the method would be made an official part of the web component's public API.

**Comment by pekam** [comment]
Adding this API for the web component is actually right now in the components sprint backlog, but the feature is not going to be included in the next minor release.

Unless this is really needed for V12, I recommend postponing this until the web component properly supports the feature.

**Comment by denis-anisimov** [comment]
@gilberto-torrezan , it's interesting but even though there is a `_onClick` method in `vaadin-grid` element instance it's not called when I click on a cell.

Apparently this method is called on some other instance and there is no any sense to override it.
But the result of this method is a `CustomEvent` which is fired.
This event already contains data which we need to identify the item where click has been done.

So I think it has sense to listen for `CustomEvent` `cell-activate`.

But in reality there is such thing as `activeItem`  property which is already a part of API.
And property listener for it `active-item-changed`  is invoked when the item is clicked.
This event contains info about clicked item.

There is only problem : no info about the original click event.
Do you see any issues with using `active-item-changed`/`cell-activate` events ?

**Comment by gilberto-torrezan** [comment]
The issue is precisely the lack of the information about the click event, such as key modifiers, number of clicks, and button clicked (left, right, middle). That's what needs to be transmitted to the server-side in order to have feature-parity with Framework 8.

**Comment by jouni** [comment]
Are we going to allow Flow developers to listen for the `active-item-changed` event as well? That would allow them to create accessible UIs that work for keyboard users the same as for mouse users.

Now, with these features added, it’s easy to create UIs that only work for mouse users 😕

**Comment by jouni** [comment]
I think it would’ve been nice if we would use the `active-item-changed` event in the client, and in the case when it was triggered with a mouse event we would add the mouse event details to the event payload. That way a Flow developer could check in the `ItemActivated` event if it was a mouse that triggered the activation, and act accordingly.

But I suppose now we’ll eventually have both `ItemActivate` and `ItemClick` events.

**Comment by pekam** [comment]
@jouni, we're working on `detailedEvents` api for the web component, after which we can change the implementation of the Flow `ItemClickListener` and `ItemDoubleClickListener` to not use `active-item` if we need to.

Then we can just listen for `detailed-click`  and `detailed-dblclick`:
https://github.com/vaadin/vaadin-grid/blob/d82b14d610d9624e9151f34172185cfe437e0d0a/demo/grid-detailed-event-demos.html#L39

**Comment by jouni** [comment]
> after which we can change the implementation of the Flow ItemClickListener and ItemDoubleClickListener to not use active-item if we need to.

I was hoping we would move to the opposite direction, though 😃 

That we would not have mouse-specific events, but rather something “input device agnostic” by default. And if you need mouse-specific functionality, there would be a way to accomplish that. That could be mouse-specific events, sure. But I was hoping to spark the discussion what would be the best alternative so that we don’t forget keyboard users.

**Comment by pekam** [comment]
Sorry, I totally misunderstood your point earlier (somehow thought the problem was that `ItemClickListener` now uses internally `active-item-changed`).

Makes sense. Even if we add the `ItemActivate` events later, it's still easier to choose `ItemClick` over that, because it's not very clear what "item activate" or "active item" means. At least we could then state in the javadocs of `addItemClickListener` that it's often a better choice to use `addItemActivateListener`, unless you explicitly want to use handle only mouse clicks.

**Comment by jouni** [comment]
Yeah, I agree that click events are the natural mental model developers will have. Documentation is the least we can do to educate them.
