### ISSUE TITLE
It should be possible to programmatically set the sort order

### ISSUE THREAD

**Issue by mvysny** [vaadin/vaadin-grid-flow#200]
Please add support for setting the currently-sorted columns from server side, by programmatically calling a sort() method. This would allow e.g. to specify the default sorting.

**Comment by mstahv** [comment]
I can easily sort the data on server side, but I'd also like to show the initial sort order in the UI somehow.

**Comment by mstahv** [comment]
Related to #13

**Comment by gilberto-torrezan** [comment]
Fixed via https://github.com/vaadin/vaadin-grid-flow/pull/290
