### ISSUE TITLE
Grid header is missing form the demo on vaadin.com

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/vaadin-grid-flow#203]
Open the link to [grid/BasicFeature](https://vaadin.com/components/vaadin-grid/java-examples/basic-features) on vaadin.com and i can get the demo in the following picture.
![image](https://user-images.githubusercontent.com/31067185/40296276-df005dec-5ce4-11e8-80e0-b153314f03c1.png)

but what i expected is:
![image](https://user-images.githubusercontent.com/31067185/40296666-efabad3a-5ce5-11e8-8170-413a27fa22cd.png)

Same thing happened with the other demos with header, like https://vaadin.com/components/vaadin-grid/java-examples/header-and-footer-rows

the vaadin.com is using `vaadin-grid-flow` `1.0.0.beta12`

**Comment by pekam** [comment]
The DOM structure seems to be correct when looking at the inspector.

The problem seems to be: 
```
GET https://vaadin.com/es6/bower_components/vaadin-grid/vaadin-grid-column-group.html 404 ()
```

**Comment by ZheSun88** [comment]
i wonder is this the same error with `vaadin-icons-flow` somehow.

**Comment by web-padawan** [comment]
Appears to be fixed now (no more 404 for `vaadin-grid-column-group.html`). Closing.
