### ISSUE TITLE
Make it possible to define sortable columns by column identifiers

### ISSUE THREAD

**Issue by mstahv** [vaadin/vaadin-grid-flow#207]
A code example of what I'd like to do:

```
grid.setSortableColumns("firstName", "lastName", "email");
```

**Comment by mstahv** [comment]
Was something done to this issue or why was it closed?

**Comment by pleku** [comment]
Shipped in 2.0.0.alpha2, which will hopefully end up in platform version V12.

**Comment by mstahv** [comment]
I didn't find a commit that fixes this issue.

**Comment by gilberto-torrezan** [comment]
Maybe the timeline only appears if you have the ZenHub plugin installed in your browser?

In any case, the PR that closed this isuee is this one: https://github.com/vaadin/vaadin-grid-flow/pull/280

**Comment by mstahv** [comment]
Thanks! Don't expect people to use anything else but GitHub.
