### ISSUE TITLE
Default sorting for "bean grid" columns happens as string comparison

### ISSUE THREAD

**Issue by mstahv** [vaadin/vaadin-grid-flow#208]
If you make a column generated by "bean grid" functionality sortable, the column is sorted by default using string comparison, which makes quite odd results (1111 before 9).

**Comment by pleku** [comment]
This is a behavior change for 1.0, but it is regression from V8 where the behavior was the one presented in this issue as the desired behavior.

THUS, if we can fix this without making breaking API changes, we can consider this as a bug and backport it to 1.0 (V10).
