### ISSUE TITLE
Getting column by header text

### ISSUE THREAD

**Issue by pekam** [vaadin/vaadin-grid-flow#22]
When a user adds a column to a grid and sets a header to it like in our demo:
`grid.addColumn(Person::getName).setHeader("Name");`
he/she might expect to be able to get the created column with:
`grid.getColumnByHeader("Name");`

If we decide to implement this:
 - this would probably work only for headers set as a `String`, and not if the header is set as a template or component.
 - additional book keeping is needed for the header-string
 - since multiple columns might have the same header, the first one would be returned
 - the javadocs might become quite complex because of the reasons above

But for a common usecase, it would provide good DX compared to separately adding a `columnKey` for retrieving your columns:
`grid.addColumn(Person::getName).setHeader("Name").setKey("Name");`
(`setKey` not yet implemented)

**Comment by pleku** [comment]
I would rather not.. this is what for we have the #17. All UI text is subject to localization and this API would make absolutely no sense for those Apps.

Closing this since we have another concept for this.
