### ISSUE TITLE
Prepare for 1.1

### ISSUE THREAD

**Issue by pleku** [vaadin/vaadin-grid-flow#228]
- make a `1.0` branch of the stable release version
  - make branch protected
  - enable validation build, sonar, cla-assistant, etc. for the branch
- UPDATE: DO NOT update `master` version to be `1.1-SNAPSHOT`, it will be done in #229 
  - the master branch should still have the validation build it has now (!)
  - make sure there is a 1.1-SNAPSHOT available for the component
- Take the `tree-grid` branch and merge it to the `master` branch
  - release a 1.1.0.alpha1
- The readme should be updated (for both branches) with the branching scheme.

**Comment by denis-anisimov** [comment]
Should the `tree-grid` branch be removed?

**Comment by pleku** [comment]
Yes the branch can be removed.
