### ISSUE TITLE
Basic Renderers for Grid

### ISSUE THREAD

**Issue by pleku** [vaadin/vaadin-grid-flow#25]
The renderers are for now just for `Grid`. There is another issue about unifying those for usage in for all components vaadin/flow#3003

We excluded `ImageRenderer` for now since we should look at feedback on what are the most typical ways of having  an image on the server side and how it generated into html.

### Acceptance Criteria
- There is the following Renders:
  - `LocalDateRenderer`and `LocalDateTimeRenderer`
  - `NumberRenderer`
  - `ButtonRenderer`
  - [`ClickableRenderer`](https://github.com/vaadin/framework/blob/master/server/src/main/java/com/vaadin/ui/renderers/ClickableRenderer.java) interface, which `ButtonRenderer` implements
- All the renderers we have for grid are listed in the documentation and explained what they might be usable for
- There a demo with all these renderers in use

**Comment by Legioth** [comment]
I.e. something corresponding to e.g. `HtmlRenderer`, `NumberRenderer` and `LocalDateRenderer` from FW8.

**Comment by gilberto-torrezan** [comment]
For the `ButtonRenderer`, does the final component should be a `<vaadin-button>` or a regular `<button>`? Should there be a way of switching one for another? 

(The HTML import for the `vaadin-button` would be a problem to solve, since there wouldn't be a component where the `@HtmlImport` could be used)

**Comment by pleku** [comment]
I would presume it is "just" a `<button>` since I can use `<vaadin-button>` myself via template renderer or component renderer. When I need to just have a button there, I don't want the performance and DX _overhead_ from having to use those, thus I would choose the `ButtonRenderer` for the convenience.

**Comment by pleku** [comment]
> All the renderers we have for grid are listed in the documentation and explained what they might be usable for
This is missing and no PR open, moving back to _In Progress_
