### ISSUE TITLE
"Toggle frozen state of ID column" has no effect

### ISSUE THREAD

**Issue by mickoyuh** [vaadin/vaadin-grid-flow#282]
Moved from Gitlab. Reported by Artur. 
--
https://vaadin.com/elements/vaadin-grid/java-examples/configuring-columns
"Column API Example"

The frozen state is not demonstrated in any way as there is no horizontal scrollbar

**Comment by web-padawan** [comment]
Demos have been updated in #472 and other PRs. Now frozen column demos have scrollbar.
