### ISSUE TITLE
If you "Toggle user reordering of columns", all grid content disappears

### ISSUE THREAD

**Issue by mickoyuh** [vaadin/vaadin-grid-flow#283]
From Gitlab. By Artur with Love. 
--
https://vaadin.com/elements/vaadin-grid/java-examples/configuring-columns

**Comment by web-padawan** [comment]
This appears to be fixed now:

![toggle](https://user-images.githubusercontent.com/10589913/74940623-63d42b80-53fa-11ea-8d18-95b229b42194.gif)

Closing as no longer reproducible.
