### ISSUE TITLE
Please add support for Grid.scrollTo()

### ISSUE THREAD

**Issue by mvysny** [vaadin/vaadin-grid-flow#289]
According to https://github.com/vaadin/vaadin-grid/issues/1187 it appears that the Grid WebComponent has support for scrolling to a particular zero-based row index. It would be great to have a server-side API of `Grid.scrollTo(int)`.

**Comment by mvysny** [comment]
The Java port would be:
```
public static void scrollTo(Grid<?> grid, int index) {
    UI.getCurrent().getPage().executeJavaScript("$0._scrollToIndex(" + index + ")", grid.getElement())
}

**Comment by pleku** [comment]
Superseded by https://github.com/vaadin/vaadin-grid-flow/issues/327
