### ISSUE TITLE
ComponentRenderer makes Grid irresponsive

### ISSUE THREAD

**Issue by pekam** [vaadin/vaadin-grid-flow#3]
@alexberazouski commented on [Wed Nov 15 2017](https://github.com/vaadin/flow/issues/2935)

Grid with ComponentRenderer freezes whole page when scrolling (or filtering).
example with pretty light Component:
http://flow.app.fi/components/vaadin-grid/using-components

-try to scroll several wheels down. Page is freezed this time
-try to scroll dragging the scrollholder. It is completely not responsive

Same happens for filtering: after call dataprovider.setFilter - it freezes page. Freeze time depends on the result size.

 It takes much more time to render, when more complex Components are used.

---

@Legioth commented on [Thu Nov 16 2017](https://github.com/vaadin/flow/issues/2935#issuecomment-344893598)

There might be two different steps to this that can be done independently:
1) Try to see if there's any avoidable overhead that can be optimized. At least https://github.com/vaadin/flow/issues/2826 could help here.
2) Make the processing done by the renderer asynchronous so that the browser doesn't freeze for long times even if there are complex components.

**Comment by pleku** [comment]
This issue will be a timeboxed investigation once the dependent issues are resolved.

**Comment by gilberto-torrezan** [comment]
The refactor made to support components with iron-list intriduced several performance improvements to the component renderer - both the `flow-component-renderer` webcomponent and the server-side counterpart mechanism. Internal tests have shown a huge improvement in the response time of Grid when using components, and this ticket can be considered fixed.
