### ISSUE TITLE
DX Test Plan for Grid

### ISSUE THREAD

**Issue by pleku** [vaadin/vaadin-grid-flow#30]
Excluded:
- Selection events
- Basic column configuration (hiding, freezing columns)

### Acceptance Criteria
There is a document that outlines the tasks for the testers to do so we can get feedback on the following features and use cases:
- Configuring renderers for a Bean that has different types of items (e.g. what renderers they use) 
- Complex header and column groups
  - might be  to ask them to put a textfield to the header to filter the column 
- Sorting (both in-memory and backend sorting)
- BeanGrid 
  - just one trivial change from id->key, should be a quick test
- Details row
  - kind of similar to FW 8, but would be nice to test to if time

**Comment by pleku** [comment]
Couple of things for how `Grid` could be tested:
- Test creating the Patient Portal Patient Entries Grid
  - it uses details row
  - Sorting enabled
  - Add filtering with search field
- Bugrap table of bugs should be created with V10 Grid and we get either the feedback
  - This might not be possible before beta

**Comment by pekam** [comment]
Dx test plan document:
https://docs.google.com/document/d/1cwQm-4FfaEeFHWnHsjJU9Wov5cMPfgF3WDMhrbYH5uM/edit#
