### ISSUE TITLE
Grid renders as a horizontal line in Firefox

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/vaadin-grid-flow#313]
@mstahv commented on [Thu Jul 05 2018](https://github.com/vaadin/flow/issues/4364)

Vaadin version: 10.0.1

With following code:

```
@Route
public class MainView extends VerticalLayout {

    public MainView() {
        Grid<String> grid = new Grid<>();
        grid.addColumn(s->s);
        grid.setItems("foo");
        add(grid);
    }
}
```

The output in FF is this:
<img width="872" alt="screen shot 2018-07-05 at 13 32 18" src="https://user-images.githubusercontent.com/1478052/42318499-e6c46014-8057-11e8-9a41-addf3c2867c9.png">

As with Safari (correct) is this:
![screen shot 2018-07-05 at 13 32 30](https://user-images.githubusercontent.com/1478052/42318505-ec412af4-8057-11e8-9758-c6d95a8f5bb0.png)

---

@samie commented on [Mon Jul 09 2018](https://github.com/vaadin/flow/issues/4364#issuecomment-403398823)

The same happens in Chrome, if `Grid.setSizeFull` method:

```
public class MainView extends VerticalLayout {
    public MainView() {
        Grid<String> grid = new Grid<>();
        grid.setSizeFull();
        grid.addColumn(s->s);
        grid.setItems("foo");
        add(grid);
    }
```

This has to do with the parent not having any reasonable size, and can be workaround using another `setSizeFull` call to the parent `VerticalLayout` class. 

However, this is not what developer expects in this simple case. More intuitive default would be just to propagate the missing size (using `setSizeFull`) to the parent, so that this situation does not happen and code above would work as expected.

---

@pekam commented on [Mon Jul 23 2018](https://github.com/vaadin/flow/issues/4364#issuecomment-407042863)

This duplicate issue has some additional details: https://github.com/vaadin/vaadin-grid-flow/issues/276
- It happens also in Edge
- It happens even after setting the height of the Grid in pixels

**Comment by KyleNehman** [comment]
I also have this issue on Firefox and calling setSizeFull on the VerticalLayout does not change anything for me. Setting a static height with setHeight makes the grid visible but this is obviously not really an answer. The only temporary work around I've come up with so far is to get the browser resolution and set the height as a ratio (yet to be implemented)

**Comment by gilberto-torrezan** [comment]
The problem happens with the interaction between `VerticalLayout` and `Grid`.

`VerticalLayout` is uses flex layout to align the items inside it, and that doesn't play well with `Grid` when the layout doesn't have a explicit size.

The easy fix for the example application is to use a `Div` instead of `VerticalLayout`.

**Comment by tomivirkki** [comment]
Fixed by https://github.com/vaadin/vaadin-grid/pull/1506

**Comment by mstahv** [comment]
Thanks @tomivirkki & @limonte, awesome work! I guess this will then end up in the next maintenance release 🤔

**Comment by mstahv** [comment]
Thank you! 😘
