### ISSUE TITLE
DataProvider not loading more than 99 entities from database.

### ISSUE THREAD

**Issue by tamimmahmudkhan** [vaadin/vaadin-grid-flow#325]
The lambda dataProvider that is shown in your vaadin tutorials on youtube does not work as intended. It loads a maximum of 99 entities. After that the grid simply loads up a lot of empty cells for whom the select event lambda doesnt work either. I used that lambda to get a count of the id value of my entity since it was increasing by 1 for each database entry. I was told to provide a simple way to recreate the problem but my whole project is the most minimal implementation meant for me to learn these libraries so I will simply link to my github repo. [link](https://github.com/tamimmahmudkhan/company-management)

**Comment by caalador** [comment]
Hi.

I tested this with your code and could scroll through a 5000 Employee list with no problems.
Also if you can get a version that recreates the problem then you should open a new ticket in : https://github.com/vaadin/framework as you are using Vaadin 8.4.4 not Vaadin Platform.
