### ISSUE TITLE
Make version with ContextMenu API that is compatible with V10 and V11

### ISSUE THREAD

**Issue by pleku** [vaadin/vaadin-grid-flow#326]
- Take latest from `1.1` and cherry-pick the context menu API and dependency to it, make a protected branch `1.2`
- Validate that it works with an example grid where context menu can be used to delete/copy items in a grid
- make sure there is a test & demo for this
- ship `1.2.0` version of Grid with this

**Comment by ZheSun88** [comment]
`vaadin-grid-flow` 1.2.0 

Check here https://repo.maven.apache.org/maven2/com/vaadin/vaadin-grid-flow/1.2.0/

**Comment by pleku** [comment]
There is no release notes in github !

**Comment by ZheSun88** [comment]
Release note is added. https://github.com/vaadin/vaadin-grid-flow/releases/tag/1.2.0
