### ISSUE TITLE
Demo jar is depending to a class that is not packaged

### ISSUE THREAD

**Issue by johannesh2** [vaadin/vaadin-grid-flow#339]
I try to embed TreeGrid demo to vaadincom and using 1.2.0. However, demo depends to some HierarchicalTestBean etc which is not packaged. Demo breaks.

**Comment by pleku** [comment]
After fixing this, should release a maintenance version of `vaadin-grid-flow` that includes the fix. Eg. `1.2.1`. (Note this is not for any platform version). The fix should be first made for `master` branch and picked to `1.2`.
