### ISSUE TITLE
Use the `path` property for `vaadin-grid-column` when applicable

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/vaadin-grid-flow#354]
The 5.2.0 version of the `vaadin-grid-column` webcomponent introduced a new property called `path`, that makes the grid render the value set under that `path` to the cells, without using a `<template>` for the column.

And since the values are rendered without template stamping, that gives a visible performance boost to large grids, specially in browsers that require polyfills for the templates.

The `path` property could be used internally for the Column when a `ValueProvider` is set (i.e. not a direct `Renderer`), which covers most of the use cases for Grid.

Details about the property can be found [here](https://cdn.vaadin.com/vaadin-grid/5.2.0-alpha5/#/elements/vaadin-grid-column#property-path).

Note that when using the path without specifying a header, the Grid shows a header based on the property name. This should be prevented to avoid strange behaviors, since the property names used by the Grid are auto-generated and don't carry any meaning.

**Comment by pleku** [comment]
>Note that when using the path without specifying a header, the Grid shows a header based on the property name. This should be prevented to avoid strange behaviors, since the property names used by the Grid are auto-generated and don't carry any meaning.

Autogenerated column names are not that bad as that is what you get now with the value provider columns. We can keep that as is (eg. not switch to use the `path`).
