### ISSUE TITLE
Problem with nested Grid in Grid-ItemDetailsRenderer on Firefox

### ISSUE THREAD

**Issue by hoermada** [vaadin/vaadin-grid-flow#362]
Hi, we´ve got the following code:

```
List<String> l = new ArrayList<>();
l.add("row 1");
l.add("row 2");
l.add("row 3");
l.add("row 4");

stringGrid.setItems(l);
stringGrid.addColumn(String::toString).setHeader("Col 1");

stringGrid.setItemDetailsRenderer(new ComponentRenderer<>(data -> {

    List<String> detailList = new ArrayList<>();
    detailList.add("detailrow 1");
    detailList.add("detailrow 2");
    detailList.add("detailrow 3");
    detailList.add("detailrow 4");

    HorizontalLayout hl = new HorizontalLayout();
    Grid<String> innerGrid = new Grid<>();
    innerGrid.setItems(detailList);
    innerGrid.addColumn(String::toString).setHeader("detail Col 1");


    hl.add(innerGrid);

    return hl;

}));
```

The nested Grid misses the first line of the given detailList. This happens only on Firefox. In Chrome there is no problem.
Chrome:
![chrome](https://user-images.githubusercontent.com/43957206/46607461-5ec25500-cb01-11e8-92b9-759c41a4ece8.png)
Firefox:
![firefox](https://user-images.githubusercontent.com/43957206/46607462-5ec25500-cb01-11e8-863c-c666ac33c083.png)

**Comment by jouni** [comment]
Also, it seems there’s a CSS leak in Firefox – the selected row style is applied to all rows in the nested grid.

**Comment by gilberto-torrezan** [comment]
By the way, what's your use case for nested Grids? Would it be something that the TreeGrid could be used instead?

**Comment by jouni** [comment]
Just a guess, but a CSS leak could also cause the first row to be hidden?

**Comment by hoermada** [comment]
Here is another screenshot from edge ... same problem

![edge](https://user-images.githubusercontent.com/43957206/46608976-b31c0380-cb06-11e8-947c-77045ad81c1d.png)

**Comment by hoermada** [comment]
sorry! close was a mistake

**Comment by gilberto-torrezan** [comment]
The same error can be reproduced with the pure webcomponent, without Flow: For example https://flannel-jewel.glitch.me/

**Comment by web-padawan** [comment]
Closing in favor of vaadin/vaadin-grid#1458 according to the above comment.
