### ISSUE TITLE
It's not possible to update rendered component if editor is used

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/vaadin-grid-flow#368]
`Grid.Column` has one extra method `setEditorComponent`  which may be shouldn't be there at all (as a public AIP).
Initially it was just a private method.
But I made it public for reasons described below:

`GridView`  contains `createBufferedEditor` method.
To be able to show and control buffered editor there is a column with "Edit" button.

The proper implementation would be:
- has a `Div`  as a container
- add **ALL** button right away into the container (`edit`, `save`, `cancel`).
- Use `setVisible` for buttons that are shouldn't be shown: `save` and `cancel` initially and when `edit` is clicked it should become hidden and `save`/`cancel` should be visible.

Using this approach you don't need any `setEditorComponent` method.

The problem is : it doesn't work in this way. `Edit` button is always shown regardless of its visibility after row becomes rendered for editing.

Everything works fine if there is no any editor involvement. But once the editor is shown via template rendering everything explodes.

Needs to be investigated since even if we have a workaround for this it's not good.

**Comment by pleku** [comment]
So to recap, for some reason, when there is a an editor component in any of the the columns, the component renderer is broken.
