### ISSUE TITLE
Disabled Grid allows deselection of rows

### ISSUE THREAD

**Issue by marcelo107** [vaadin/vaadin-grid-flow#379]
A grid with `SelectionMode` set as `Multi` allows the deselection of already selected rows. 
![Disabled_MultiSelection_Grid](https://user-images.githubusercontent.com/13228078/47292004-1c5a4700-d5dc-11e8-918f-f5bf3f12efcb.png)
The disabled attribute and styles are present and it is not possible to select non-selected rows (as expected)
![HTML_CSS_Grid](https://user-images.githubusercontent.com/13228078/47292088-5af00180-d5dc-11e8-8027-5982646e89ee.png)
However, it is possible to deselect the selected rows. In the example below I delesected two of the three selected rows.
![Deselection](https://user-images.githubusercontent.com/13228078/47292200-a73b4180-d5dc-11e8-987e-4108fb131cfd.png)
It is also possible to select the "select all" checkbox (which I believe is not something that you would expect of a disabled grid).
![Select_checkall](https://user-images.githubusercontent.com/13228078/47292258-cdf97800-d5dc-11e8-9c7e-524e9f8faaa9.png)

Tested with Vaadin 10.0.6 on Chrome.

**Comment by marcelo107** [comment]
Also happens with single selection. A simple test was made on the https://vaadin.com/components/vaadin-grid/java-examples on the disabled grid part. With the grid enabled select any row, then disable the grid and select the selected row. It will deselect that row.

**Comment by caalador** [comment]
After looking at the functionality for a while one can notice that the server doesn't get a deselect event for the disabled grid and the server-side selection doesn't change.

Also when enabling the grid again the selection is reset to the expected value. 

Same for the multi-select selections. Will investigate further that where the issue should be fixed.
