### ISSUE TITLE
Prototype cell class generator API

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-grid-flow#390]
This is a research ticket for https://github.com/vaadin/vaadin-grid-flow/issues/185

Collaborate with https://github.com/vaadin/vaadin-grid/issues/1297 in order to find best API/implementation for both ends of the component.

There's an experimental branch for the web component feature that could be initially used for prototyping the Flow counterpart.

Take inspiration for the API from V8 grid cell class generators.

**Comment by pekam** [comment]
Here's a prototype with style generators and class generators for columns, rows and cells:
https://github.com/vaadin/vaadin-grid-flow/compare/style-generator
