### ISSUE TITLE
Make IT tests for various usecases of dynamically generated editor feature

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/vaadin-grid-flow#397]
The original ticket is #358
Some implementation is available here https://github.com/vaadin/vaadin-grid-flow/tree/gilberto/358_editor_callback.

There are various usecases which should be covered by the tests:
- `null`  editor : it should be possible to disable editor at all for some rows
- basic usecase should work : specifying various editors per different row
- update the editor components on the fly (if user changes the data in some component the other there should be a way to update other components based on new data).
- various corner cases (needs to be seen from the suggested implementation).

**Comment by pleku** [comment]
Also please validate that the keyboard navigation works like it should
