### ISSUE TITLE
Grid Editor with callback(s) for dynamically generating the editor

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/vaadin-grid-flow#398]
Based on the spike described on https://github.com/vaadin/vaadin-grid-flow/issues/358

> As based on feedback from #324, there should be a way to specify the editors for a certain grid column on the fly based on the bean instance - meaning it that there might be different editor components used for the same column on different rows.

The API should be: 

Dynamic component:
```java
setEditorComponent(item -> item.isCountry() ? getCountryEditor() : getCityEditor());
```

Dynamic binding:
```java
setEditorBinding(item -> item.isSubscriber() ? binder.bind(emailField, "email") : null);
```

There should be possible to return `null` components and bindings, which would mean the same as not having any editor for the column (for that item).

Setting a static component or binding should override the dynamic setting, and setting the dynamic binding or component should override the static one. In other words, the last method used, wins.

When using `setEditorComponent/setEditorBinding` with the lambdas, the respective `getEditorComponent/getEditorComponent` should return `null`.

**Comment by gilberto-torrezan** [comment]
ITs are covered by the ticket https://github.com/vaadin/vaadin-grid-flow/issues/397

**Comment by pleku** [comment]
### Acceptance Criteria
- There is a demo with Grid editor feature that uses
  - a column where there is no editor (eg. ID)
  - a column with static editor
  - a column with dynamic editor, based on eg. whether the user has rights or for changing this or not
- There is another demo with Grid editor feature that uses
  - in any column a dynamic editor that it has the component changed on the fly based on the value that has been changed in another column

The demos can be merged if it is still says simple enough, but might be feasible to keep them separate, as the second demo with dynamically changing the editor on column B based on column A value is quite complex example.
