### ISSUE TITLE
Make editor IT tests stable

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/vaadin-grid-flow#402]
Currently the generated data is used to test Grid editor functionality.
It works only as soon as we don't modify the `Person`  bean with new properties ( or remove the existing ones) since for data generation generation the hardcoded permanent seed is used.

But if a new property is added to the `Person` class ( or removed) the generated data is changed.
That leads to tests failure and you will have to update the tests (which you are not even aware of).

To avoid this issue I've made a correction to the test data: the very first (and second) row are hardcoded and are not generated. Such approach is used e.g. in `createColumnTemplate` demo.

Now the editor tests uses the generated data which are not stable in a sense above.

They should be made stable.
There are two ways:
- use the same approach that I've used previously with hardcoded data
- use a new instance of `Random` for every property to generate data ( so there will be 1:1 with a property and a `Random` instance). Currently the same `Random`  instance is used for all properties.

In case of second approach please correct the existing data and tests which are using the hardcoded data to unify the code.

**Comment by gilberto-torrezan** [comment]
Closed via #403
