### ISSUE TITLE
The demo for inline editor in non-buffered mode has crappy UX

### ISSUE THREAD

**Issue by pleku** [vaadin/vaadin-grid-flow#406]
When the user tabs out from the last editor from the row (or to other direction), the editor should be closed. This is one of the basic use cases for the inline editor, to be able to fast editing of the data.

Currently after pressing tab on the last editor, the focus goes back to the first cell of the row and the editors stay open. As a user, I would expect the focus to go to the next row instead and the editor to be closed. It should be possible to achieve this UX with the editor.

**Comment by denis-anisimov** [comment]
May be I'm missing something but I don't see how this can be done in easy way (using some existing Grid or whatever functionality).

I can add a listener for a `Tab` event via JS and based on conditions close the editor via calling server side function.

But I have no any idea how I can move keyboard focus to the next row.
In reality I don't see any way to do this using keyboard or mouse actually.
And I don't see how it can be useful: if you don't have any input component in your grid then keyboard focus on a cell doesn't allow to do anything.

So when the editor is closed the focus stays on the very first cell of the same row (and then leaves the Grid on subsequent Tab).

Is it OK or should I find a way to move keyboard focus to the first cell of the next row?

Another question is : should this be implemented as a standard not-buffered editor feature or it's only a demo issue ?

I can solve this issue for the demo via JS calls but it will requires some efforts to make this implemented by default as a not-buffered editor.

The challenges are:
- the very first and the very last editor components need to be identified and they can be changed if reordering/column modification happens.
- what to do if user don't want this default behavior ?

**Comment by denis-anisimov** [comment]
OK, in case of dynamic editor it looks like it's just impossible to have this functionality generically implemented in `Grid` editor. So I will implement this in demo only.
But as I said I don't see how I can put keyboard focus on the next row instead of having the default behavior. So the editor will be closed but focus will behave the same way as currently.
