### ISSUE TITLE
DataProvider.refreshItem(T item) causes reset of all DOM for Grid

### ISSUE THREAD

**Issue by pleku** [vaadin/vaadin-grid-flow#419]
Apparently this is due to the way the client side caching is updated at the moment, by discarding the currently shown page in web component, causing all the rows to be rendered again, which can be a big overhead for a complex grid and causes bad UX due to slowness.

**Comment by pleku** [comment]
This fix should be backportable to 1.0 version of the Grid (V10).

**Comment by gilberto-torrezan** [comment]
Here is the call made by the `gridConnector` when an item is updated: https://github.com/vaadin/vaadin-grid-flow/blob/2.1.0/src/main/resources/META-INF/resources/frontend/gridConnector.js#L412

The refresh of the items itself is handled by the webcomponent.
