### ISSUE TITLE
Issues with Flow 1.0.0.alpha13

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-grid-flow#43]
Current Grid release in the BOM has serious issues with current Flow release also in the BOM.

```
(TypeError) : grid._createPropertyObserver is not a function
The error has occurred in the JS code: '$0, window.gridConnector.initLazy($0)'
(TypeError) : $0.$connector.setSelectionMode is not a function
The error has occurred in the JS code: '$0, $1, $0.$connector.setSelectionMode($1)'
...
```

See https://github.com/vaadin/flow/issues/3137.

**Comment by Legioth** [comment]
This happens because the collection annotation for multiple HTML imports has been renamed, but the Grid component hasn't been recompiled to use the new name.

As a workaround, you can add `@HtmlImport("bower_components/vaadin-grid/vaadin-grid.html")` to the view that uses Grid.

**Comment by heruan** [comment]
Note that the workaround works only if there are no component-rendered columns, otherwise `master` is needed to have #40.

**Comment by heruan** [comment]
Working with Flow `alpha14` and Grid `alpha4` 👍
