### ISSUE TITLE
A problem in Basic features of Grid demo.

### ISSUE THREAD

**Issue by shadikhani** [vaadin/vaadin-grid-flow#432]
In https://vaadin.com/components/vaadin-grid/java-examples/basic-features at the bottom of the page there is a for loop as follows:

for (String company : companies) {
            Map<Integer, YearlyBudgetInfo> budgetHistory = new HashMap<>();
            for (int year = baseYear; year < baseYear + numYears; year++) {
                YearlyBudgetInfo budgetInfo = new YearlyBudgetInfo(
                        getRandomBigDecimal(), getRandomBigDecimal());
                budgetHistory.put(year, budgetInfo);
            }

The variable "companies" is not defined anywhere, and I think it should be fixed.

**Comment by ZheSun88** [comment]
you can get it here.. https://github.com/vaadin/vaadin-grid-flow/blob/master/src/test/java/com/vaadin/flow/component/grid/demo/GridView.java#L1794-L1831

Maybe we should include this in the demo . or just generate some random ones.

**Comment by tmattsso** [comment]
Zhe, if any user copies that code and tries to run it, it fails. The demo should include a few hardcoded users as test data, not rely on a magic separate class to provide the data.

**Comment by caalador** [comment]
Just to note that the old sampler also has in the sources `ExampleUtil.getBudgetDataProvider(baseYear, numberOfYears);` so perhaps it would be more beneficial to have a clear link to a place where all the used data can be gotten from.

**Comment by web-padawan** [comment]
There has been a lot of demo changes done in #472 and other PRs. This should be fixed now.
