### ISSUE TITLE
Issue with row details visibility

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-grid-flow#433]
When a Grid is `setHeightByRows(true)` and `setDetailsVisibleOnClick(true)`, when clicking a row the details open but the grid height doesn't change so that some rows and/or part of the detail aren't visible anymore.

I would expect the height of the grid to adapt when details are opened.

**Comment by heruan** [comment]
Well, it's not just with `setHeightByRows(true)` but with details in general.

This replicates: [GridWithDetails](https://github.com/heruan/vaadin-spring-demo/blob/82486df21151a8fe3b5fecfbb8183df47896b8e8/src/main/java/to/lova/vaadin/spring/GridWithDetails.java)

1. run with `mvn spring-boot:run`
2. go to http://localhost:8080/grid-with-details
3. click on the first row: details are not shown entirely

**Comment by caalador** [comment]
One thing I noted when testing is that it happens only when using `ComponentRenderer`, but not for `TemplateRenderer`.

**Comment by bbaumgartner** [comment]
We found the same issue when trying to update to vaadin 12. It works fine in 11.0.3 but is broken in 12.beta2.

**Comment by evanzel** [comment]
This is still an issue for Vaadin 12.0.2.
10 and 11 branches are ok.

**Comment by poczenorbert** [comment]
Same for Vaadin 12.0.3

**Comment by bbaumgartner** [comment]
I'm starting to be a bit concerned about this Issue. It's a blocker for Vaadin 12 update on our side and this issue has no assignee and no milestone set.
Is anyone aware of a workaround (other than writing a grid myself:-) Is it maybe possible to open->close->open programmatically to work around it?

**Comment by bbaumgartner** [comment]
Thank you tomivirkki, the workaround works for me too.
`protected void expand(RowType row) {
    grid.setDetailsVisible(row, !grid.isDetailsVisible(row));
    grid.getElement().executeJavaScript("requestAnimationFrame((function() { this.notifyResize(); }).bind(this))");
}`

**Comment by tomivirkki** [comment]
Submitted a PR that basically applies the above workaround to the Web Component. https://github.com/vaadin/vaadin-grid/pull/1531 Not 100% sure if it's enough to fix this particular issue so didn't yet annotate it with "fixes"

**Comment by tomivirkki** [comment]
Verified that https://github.com/vaadin/vaadin-grid/pull/1531 fixes the issue in `<version>5.2.6</version>` that should be included in the next V12 maintenance release.

**Comment by bbaumgartner** [comment]
Thank you Tomi
