### ISSUE TITLE
Update Grid Java demos to be more sensible: columns, headers, footers, renderers, templates, components, item details

### ISSUE THREAD

**Issue by tmattsso** [vaadin/vaadin-grid-flow#434]
The demos should demonstrate use cases, not features. Me and Artur did a go-through of all current demos, and came up with a list of fixes. 

https://docs.google.com/document/d/1iNnXFQ4WtGsbkh5jqtccxqml5XjBVyqBFH4ttpapoB0/edit

This ticket is a subset because the list is so big. For this ticket, the areas are:

Configuring Columns

- Column API example
- Make demo work
- Call this "Manually defining columns"
- Use a value provider which does something else than a getter, e.g. combines two properties
- Do not configure ALL THE THINGS in the demo, it's enough to give the idea where the API is found
- Remove unnecessary code like `setKey`
- Add frozen columns example
- Add column alignment example
- Automatically adding columns
- Make this the first demo, call it "Configuring columns" 

Header and Footer Rows

- Rename to "Header and Footer"
- Add a first example which is "Header and footer texts"
- Set header texts to something custom which makes sense
- Add a footer which calculates the average age
- "Adding header and footer rows"
- Rename to "Column grouping"
- Use some more sensible data like in year/half/quarter grouping
- Possible use "Grid Basic Features Demo"  from "Basic Features"
- Sum in footer with same division
- "Header and footer using components"
- Rename to "Using components"
- Replace by a sensible demo using components, not Labels, WTF
- Simple idea would be button base filtering for age "-20, 20-40, 40-"

Using Renderers & Using templates

- Rename into "Formatting Contents"
- Using basic renderers
- Rename to "Formatting text"
- Make it a read-only example
- Remove the IconRenderer
- Grid with columns using template renderer
- Rename to something which describes why you would use it and for what
- If there is no case, remove the demo

Using Components

- Grid with columns using component renderer
- Rename to "Using components"
- Render name as you would otherwise, add the remove column with a remove button
- Use Button and not NativeButton
- Remove the strange form below the grid
- Remove the ItemDetailsRenderer
- Add demo here 

Item Details 

- Grid with item details
- Remove "Update person" - it makes no sense
- Consider adding an image as in the HTML example -  looks much nicer
- Open details programmatically
- Remove "Update person" - it makes no sense

**Comment by web-padawan** [comment]
There has been a lot of demo changes done in #472 and other PRs.
Please open a new issue if something from this list wasn't covered.
