### ISSUE TITLE
Update Grid Java demos to be more sensible: selection, sorting and filtering

### ISSUE THREAD

**Issue by tmattsso** [vaadin/vaadin-grid-flow#435]
The demos should demonstrate use cases, not features. Me and Artur did a go-through of all current demos, and came up with a list of fixes. 

https://docs.google.com/document/d/1iNnXFQ4WtGsbkh5jqtccxqml5XjBVyqBFH4ttpapoB0/edit

This ticket is a subset because the list is so big. For this ticket, the areas are:

Generic problems:

- Buttons do not look like buttons
- A new user should be able to understand in 10 seconds what a given demo is about
- Do not start demo headers with "Grid ", everything is about grid
- Sync demo headers and categories with HTML examples whenever possible
- Use new Grid(Person.class) in most demo to avoid doing a lot of extra column configuration

Selection

- Grid single selection
- Remove the "select first" button
- Grid multi selection 
- Programmatic selection
- Add new demo showing how to select item/items from Java
- Remove Grid no selection - it's not very interesting

Sorting

- Grid with sortable columns
- Use new Grid(Person.class) by default and show it's sortable
- Remove debug info "Current sort order: {sort property: name, direction: ASCENDING}. Sort originates from the client: true."
- Add example on doing backend sort with Spring Boot service / repository

Filtering

- Move after sorting
- Using text fields for filtering items (from Filtering)
- Rename to "Basic filtering" or something similar
- Data type specific filters
- Add demo showing how to use ComboBox (for enum) and DateField (for LocalDate) filters in the header

**Comment by web-padawan** [comment]
There has been a lot of demo changes done in #472 and other PRs.
Please open a new issue if something from this list wasn't covered.
