### ISSUE TITLE
Update Grid Java demos to be more sensible: basics and assigning data

### ISSUE THREAD

**Issue by tmattsso** [vaadin/vaadin-grid-flow#436]
The demos should demonstrate use cases, not features. Me and Artur did a go-through of all current demos, and came up with a list of fixes. 

https://docs.google.com/document/d/1iNnXFQ4WtGsbkh5jqtccxqml5XjBVyqBFH4ttpapoB0/edit

This ticket is a subset because the list is so big. For this ticket, the areas are:

Generic problems:

- Buttons do not look like buttons
- A new user should be able to understand in 10 seconds what a given demo is about
- Do not start demo headers with "Grid ", everything is about grid
- Sync demo headers and categories with HTML examples whenever possible
- Use new Grid(Person.class) in most demo to avoid doing a lot of extra column configuration

Basic Usage

Grid Basics
- Minimize the code needed (use new Grid(Person.class})
- Add a couple of hard coded persons created in the code instead of using a hidden `getItems` method (e.g. setItems(Arrays.of(new Person("John","Doe")...))`
- No need to set the headers separately
Grid with lazy loading
- Minimize the code needed (use new Grid(Person.class})
- Extract the data provider into a separate class and somehow cleanup the code. Maybe highlight only the method which generates a person. 
- No need for header setting
Disabled grid
- Remove. This demo makes absolutely no sense
Grid example model
- Show after first demo if it can't be shown as a separate black box in the first demo
- Replace all getters/setters/toString/hashCode with `// + getters and setters`

Height by Rows

- Remove category

Basic Features

- Remove category

Assigning Data (available only in HTML examples)

- Add an example on how to use a Spring Data backend
- Add the "Dynamic Array Data" from the HTML part, i.e. show how you can add/remove items when using in memory data. Mention in text that this can be done for lazy data also and how
- Add "Dynamic Height" from the HTML part, i.e. show how grid can be full height even when you add/remove rows

**Comment by web-padawan** [comment]
There has been a lot of demo changes done in #472 and other PRs.
Please open a new issue if something from this list wasn't covered.
