### ISSUE TITLE
Vaadin Grid Demos

### ISSUE THREAD

**Issue by shadikhani** [vaadin/vaadin-grid-flow#461]
Some parts of Vaadin demos need to be reviewed later by DJO team like TreeGrid, Click Listener, ContextMenu and Grid Editor.

**Comment by denis-anisimov** [comment]
I don't think I understand what it is...
Is this a bug? Then what should I do to fix it.
Is it an enhancement ? Again : what should I do?

This looks as a reminder for yourself. But please make a reminder either in your tracker or somewhere in other place.
The problem with this : I don't understand **_what_** I need to do and **_when_**. As a result this will be either forgotten or never done.

I'm closing this. Please let me know if there are exact actions to do.

**Comment by shadikhani** [comment]
Yes, you're right. I should have put it in the Trello. It is a reminder for some grid demos to be reviewed later.
