### ISSUE TITLE
Can't set a column sort order in Vaadin10+, but the classes to build/manage it are still present

### ISSUE THREAD

**Issue by abierlerxdev** [vaadin/vaadin-grid-flow#462]
Vaadin 8 contains a method to set the column sort order in Grid:
[setSortOrder](https://vaadin.com/api/framework/8.6.3/com/vaadin/ui/Grid.html#setSortOrder-com.vaadin.data.provider.GridSortOrderBuilder-)

However this method is missing in Vaadin10+, but the classes to manage sort orders still exist:
[GridSortOrder](https://vaadin.com/api/platform/12.0.2/com/vaadin/flow/component/grid/GridSortOrder.html)
[GridSortOrderBuilder](https://vaadin.com/api/platform/12.0.2/com/vaadin/flow/component/grid/GridSortOrderBuilder.html)

**Comment by denis-anisimov** [comment]
There is `Grid:sort` method.
I think it should does what you want.
At least it delegates to the private  `setSortOrder` method.

Please reopen if it doesn't work for you.

**Comment by Legioth** [comment]
Could be mentioned that `Grid::sort` was introduced with Vaadin 12, but is not available for Vaadin 10 or Vaadin 11.
