### ISSUE TITLE
Horziontal Scroller in the TreeGrid is missing

### ISSUE THREAD

**Issue by abierlerxdev** [vaadin/vaadin-grid-flow#471]
If you have long text in a little TreeGrid, the text get's cut off and no scrollbar appears.

### How to reproduce
I use the following code:
```
@Route("")
public class TreeGridDemo extends HorizontalLayout
{
	private final TreeGrid<Project> treegrid = new TreeGrid<>();
	
	public TreeGridDemo()
	{
		// Build a Project-Structure
		final Project main = new Project("Main");
		
		final Project sub1 = new Project("Sub1");
		sub1.setParent(main);
		
		final Project sub1_1 = new Project("Sub1_1_Extreme_long_text_that_is_here_and_you_can't_see_it_:/");
		sub1_1.setParent(sub1);
		
		final Project sub1_2 = new Project("Sub1_2");
		sub1_2.setParent(sub1);

		//Generate some Subprojects
		final List<Project> subs = new ArrayList<>();
		for(int i = 1; i < 20; i++)
		{
			final Project p = new Project("Auto generated SubProject"+i);
			p.setParent(main);
			subs.add(p);
		}
		
		final TreeData<Project> treedata = new TreeData<>();
		
		// Add structure to the TreeData
		treedata.addRootItems(main);
		
		treedata.addItems(main, sub1);
		treedata.addItems(main, subs);
		treedata.addItems(sub1, Arrays.asList(sub1_1, sub1_2));
		
		// Set the data into the TreeGrid
		this.treegrid.setTreeData(treedata);
		this.treegrid.addHierarchyColumn(Project::getName);
		
		//Other component(s) that need a lot of space
		final Div othercomp = new Div();
		othercomp.setWidth("85%");

		this.add(this.treegrid, othercomp);
	}
	
	public class Project
	{
		private String name = "";
		
		private List<Project> subprojects = new ArrayList<>();
		private Project parent;
		
		public String getName()
		{
			return this.name;
		}
		
		public void setName(final String name)
		{
			this.name = name;
		}
		
		public List<Project> getSubprojects()
		{
			return this.subprojects;
		}
		
		public void setSubprojects(final List<Project> subprojects)
		{
			this.subprojects = subprojects;
		}
		
		public Project getParent()
		{
			return this.parent;
		}
		
		public void setParent(final Project parent)
		{
			this.parent = parent;
			this.parent.getSubprojects().add(this);
		}
		
		public Project(final String name)
		{
			this.name = name;
		}
	}
}
```

Open the first node "Sub1" or look at the auto generated nodes (depends on display used, screen resolution, etc.). 
The text they contain is getting cut off.

### Result
Something like this:
![grafik](https://user-images.githubusercontent.com/45384811/50207323-6bb7bc00-036e-11e9-9b8a-e71aaa45f7ab.png)

**Comment by jouni** [comment]
The grid is behaving as expected.

The column width is not explicitly defined, so it is using the default 100px width. By default all columns also have “flex=1”, so here when there’s only one column all the remaining space of the grid (after reducing 100px) is allocated to to it. So the one column effectively takes the full width of the grid, but not more. If you shrink the grid below 100px, then you’ll get a horizontal scrollbar.

Also, as the data is fetched lazily from the server, the width of the column is not known until the rows are expanded to show the child items.

Potential solutions:

1. Approximate the width of the longest text and use `em` based width for the column. E.g. if the longest text is 40 characters long, set the column width to `40em`.

2. Utilize the recently added column "auto width” feature. It won’t work out-of-the-box if the longer texts are loaded after expanding a node, and you will need to call the `recalculateColumnWidths()` JS method on the grid after a node has been expanded.

3. Allow the end users to resize the column so they can grow the width enough to see the content.

I’m closing this issue as invalid. If you wish some of this behavior would be changed or improved, or that there would be some more configuration options, please open new issues for those.

**Comment by Peppe** [comment]
I was investigating this as well so I might add some examples and insights.

It happens also on top level items, so this code works pretty much the same way.
```
@Route("horizontal-scroll")
public class HorizontalScrollGrid471 extends VerticalLayout {
	public HorizontalScrollGrid471() {
		TreeGrid<String> treegrid = new TreeGrid<>();
		final TreeData<String> treedata = new TreeData<>();
		treedata.addRootItems("A longer row name that will not fit the component");
		treegrid.setTreeData(treedata);
		treegrid.addHierarchyColumn(String::toString)
		treegrid.setWidth("100%");
		add(treegrid);
		setWidth("200px");
	}
}
```
You can fix this by ading setAutoWidth(true) on row 8.
```
treegrid.addHierarchyColumn(String::toString).setAutoWidth(true);
```

Similarily in your example you can change:
```java
this.treegrid.addHierarchyColumn(Project::getName)
```
to
```
this.treegrid.addHierarchyColumn(Project::getName).setAutoWidth(true);
this.treegrid.addExpandListener((event) -> {
  this.treegrid.recalculateColumnWidths();
});
```

You need it to be recalculated after it has new content. There's however seems to be a problem that the recalculation happens before the expansion, and you have to toggle an additional node to get it right, if the latest expanded node had the longest data.

**Comment by abierlerxdev** [comment]
Note:

```java
this.treegrid.addExpandListener((event) -> {
  this.treegrid.recalculateColumnWidths();
});
```
doesn't work in Vaadin 14.


You need to call this after the items inside the Grid are rendered
```java
public static <T> void recalculateColumnWidthsOfGrid(final Grid<T> grid)
{
	final UI currUI = UI.getCurrent();
	CompletableFuture.runAsync(() ->
	{
		try
		{
			Thread.sleep(200);
		}
		catch(final Exception e)
		{
			// Happens...
		}
		
		currUI.access(() -> grid.recalculateColumnWidths());
	});
}
```
→ https://github.com/vaadin/vaadin-grid/issues/1629
