### ISSUE TITLE
Freeze selection column

### ISSUE THREAD

**Issue by brp-oskar** [vaadin/vaadin-grid-flow#48]
I would like to be able to freeze the selection column. I can't find a way to do that with the current api.

I modified the demo example `GridView::createMultiSelect()` with the current lines:

```
grid.addColumn(Person::getName).setHeader("Name").setFrozen(true);
grid.addColumn(Person::getAge).setHeader("Age").setWidth("500px");
grid.addColumn(Person::getAge).setHeader("Age").setWidth("500px");
grid.addColumn(Person::getAge).setHeader("Age").setWidth("500px");
```

It gives the following behaviour, which is expected. But how do I freeze the selection column?

![image](https://user-images.githubusercontent.com/7449335/34117552-502acf4e-e41c-11e7-8fde-908f05caff85.png)

**Comment by denis-anisimov** [comment]
Will be `GridMultiSelectionModel::setSelectionColumnFrozen` and `GridMultiSelectionModel::isSelectionColumnFrozen`.
