### ISSUE TITLE
OSGi: ERROR: bundle com.vaadin.flow.component.grid:2.1.3 (89)Component descriptor entry 'OSGI-INF/com.vaadin.flow.component.grid.osgi.GridContributor.xml' not found

### ISSUE THREAD

**Issue by enver-haase** [vaadin/vaadin-grid-flow#487]
Start up the base-starter-flow-osgi and see

ERROR: bundle com.vaadin.flow.component.grid:2.1.3 (89)Component descriptor entry 'OSGI-INF/com.vaadin.flow.component.grid.osgi.GridContributor.xml' not found

in the log on screen.

**Comment by pleku** [comment]
Fixed with https://github.com/vaadin/flow-component-base/issues/116 since 12.0.3
