### ISSUE TITLE
Theme not applied to Vaadin-button in grid.

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-grid-flow#489]
_From @martinisraelsen on January 22, 2019 21:13_

I have a grid with a Vaadin-button on each row. The Vaadin button is themed (primary) but it is showing as a regular button (grid1).

Oddly enough, if I add another button after the grid, the buttons in the grid are rendered correctly (grid2).

![grid1](https://user-images.githubusercontent.com/6271003/51565681-3b28dd80-1e58-11e9-8c72-a08cc80dcf50.png)
![grid2](https://user-images.githubusercontent.com/6271003/51565682-3b28dd80-1e58-11e9-8447-616630e2f484.png)

Source code attached in zip.

[grid.zip](https://github.com/vaadin/vaadin-grid/files/2784625/grid.zip)

_Copied from original issue: vaadin/vaadin-grid#1547_

**Comment by martinisraelsen** [comment]
@web-padawan That makes sense - will a regular HTML import of the button be sufficient?

**Comment by web-padawan** [comment]
@martinisraelsen yes, please try adding HTML import and let us know if that helps.

**Comment by martinisraelsen** [comment]
@web-padawan Works perfectly fine if I add an import such as: 

```
@HtmlImport("bower_components/vaadin-button/src/vaadin-button.html")
```

@web-padawan your explanation makes perfect sense and I recon it's not a bug, but just how Flow works.

That being said, I'm sure others will run into the same issue. I don't recall having seen any notes about having to manually import vaadin-* components when using them with a template renderer. 

It would be good to have a note in the Flow documentation 

https://vaadin.com/docs/v12/flow/Overview.html

and the grid component page

https://vaadin.com/components/vaadin-grid/java-examples

**Comment by web-padawan** [comment]
Submitted vaadin/flow-and-components-documentation/issues/1106 to document that.
We can's show that in demos, because our demos don't contain any imports.

Closing as answered per above comment.

**Comment by Legioth** [comment]
Rather than duplicating the original import, e.g. `@HtmlImport("bower_components/vaadin-button/src/vaadin-button.html")`, I would recommend that you reuse it (along with anything else that a future version of the button component may nee) with an annotation like `@Uses(Button.class)`.
