### ISSUE TITLE
Fix TreeGrid demo

### ISSUE THREAD

**Issue by tmattsso** [vaadin/vaadin-grid-flow#501]
I looked a the demo, it's horrible. here is a list of things to improve:
	basics
- the demo data makes no sense whatsoever.. random persons, under each other? This needs better demo data, something naturally hierarchical.
- why have a form? remove it.
- why the ´logging output window´? remove it.
buttons; change ´toggle´ to ´expand´ and ´collapse´ (if expanded). only one button is enough.
		
- The code sample uses methods that aren't shown, such as ´getRootItems´ and ´createSubItems´. The whole setItems method is unclear, it takes two parameters; what does the second do? why are there no comments anywhere?
		
- remove the listeners from the demo, they aren't relevant to the demo functionality and can be easily discovered.
		
lazy loading
- again, what is this demo data??
- demo buttons; remove them all, the feature was already demonstrated above.
		
- the whole dataprovider needs a re-think; the code is unreadable. and why is there an internal method for hasChildren?
- if the point is to show lazy loading, why don't you explain that in the demo or code?

**Comment by vyomrastogi** [comment]
Any suggestions on a better lazy loading example ? I tried following example, but not able to understand.

**Comment by web-padawan** [comment]
TreeGrid demos have been updated by #621. Please open a new issue if something wasn't fixed.
