### ISSUE TITLE
Grid item details height/position bug

### ISSUE THREAD

**Issue by nemojmenervirat** [vaadin/vaadin-grid-flow#535]
**Description of the bug**
Grid item details not showing correctly in 12.0.3.  Its working in 10.0.9 and 11.0.3. I've used _Project Base with Spring_ starter. Same effect as in #3747, but now it happens even if it is not async.

**Minimal reproducible example**
```
@Route
public class MainView extends VerticalLayout {
	
	public class Person {

		private String firstName;
		private String lastName;

		public String getFirstName() {
			return firstName;
		}

		public void setFirstName(String firstName) {
			this.firstName = firstName;
		}

		public String getLastName() {
			return lastName;
		}

		public void setLastName(String lastName) {
			this.lastName = lastName;
		}

	}

	public MainView() {
		Grid<Person> grid = new Grid<>(Person.class);
		grid.setItemDetailsRenderer(new ComponentRenderer<>(e -> new VerticalLayout(new Button("DO SMTH"), new Button("DO SMTH ELSE"))));
		grid.setItems(getData());
		add(grid);
	}

	private Collection<Person> getData() {
		List<Person> persons = new LinkedList<>();
		{
			Person person = new Person();
			person.setFirstName("John");
			person.setLastName("Smith");
			persons.add(person);
		}
		{
			Person person = new Person();
			person.setFirstName("Jovan");
			person.setLastName("Kovac");
			persons.add(person);
		}
		{
			Person person = new Person();
			person.setFirstName("Mickey");
			person.setLastName("Mouse");
			persons.add(person);
		}
		return persons;
	}

}

```

**Expected behavior**
![image](https://user-images.githubusercontent.com/3105705/50119482-310d3100-0253-11e9-90d8-d08d0c28233f.png)

**Actual behavior**
![image](https://user-images.githubusercontent.com/3105705/50119569-6e71be80-0253-11e9-8c65-ac4b8034db90.png)

**Versions**
Vaadin 12.0.3
Java 1.8
Spring 2.1.0.RELEASE
Browsers: Chrome, Firefox, Edge (latest versions)

**Comment by tomivirkki** [comment]
![Kapture 2019-10-16 at 12 56 12](https://user-images.githubusercontent.com/1222264/66909369-4e4a9180-f015-11e9-83c5-86d2df6a1512.gif)

Seems that the issue got fixed somewhere along the way. The above recording is using the provided code snippet (Platform version 14.0.9). I'll close this issue unless another example where the issue produces is provided.

**Comment by tomivirkki** [comment]
Closing, please reopen if still relevant

**Comment by nemojmenervirat** [comment]
Yes it's fixed.
