### ISSUE TITLE
Decorating List<> data

### ISSUE THREAD

**Issue by KamrulHasan-Seu** [vaadin/vaadin-grid-flow#574]
I have a list of data in my database. When I set it in the grid it shows like :
![capture](https://user-images.githubusercontent.com/39347965/53882894-bf6aa500-4041-11e9-8bf5-366ac1eb29fe.PNG)

How can I set it just by name? Or is there any component to see these details?

**Comment by denis-anisimov** [comment]
This is not a bug.
This is a question.
Please use https://vaadin.com/forum/ for questions.

I have no idea how you add your column or how you create you `Grid` instance.
`Grid` has a method  `addColumn(ValueProvider<T, ?> valueProvider)`. If you provide the correct `ValueProvider`  which produces what you need in the column then you will get what you want.
