### ISSUE TITLE
New column with ComponentRenderer is not rendered immediately

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/vaadin-grid-flow#587]
Minimal example, tested on Vaadin 13.0.1 with Windows 10 on Chrome, Edge and FF:
```
public class MainLayout extends VerticalLayout {

    protected Grid<String> grid;

    public MainLayout() {
        setSizeFull();
        grid = new Grid<String>();
        grid.addColumn(new ComponentRenderer<>(item -> new Span("test"))).setHeader("Test");
        grid.setItems("Foo");
        add(grid);
        Button btn = new Button("Add new column with Span ComponentRenderer");
        btn.addClickListener(e -> {
            grid.addColumn(new ComponentRenderer<>(item -> new Span("test new"))).setHeader("new column");
        });
        add(btn);
    }
}
```
When clicking the button, the new column's contents are not rendered until a server round trip happens (eg. another click of the same button).

**Comment by JoeBrig** [comment]
I'm noticing that ComponentRenderer grid columns will sometimes never render.  The occurrence of this increases the longer the application has been running.  The problem goes away after a server side restart, but always returns.

**Comment by anasmi** [comment]
The same issue using `LocalDateRenderer`. 
Adding column on some action doesn't display the data immediately. 
The whole example (the same logic as in Olli's example):
```
@Route( value= "grid-view",layout = MainView.class)
public class GridView extends VerticalLayout {

        public GridView(){
                Grid<String> grid = new Grid<String>();
                grid.addColumn(string->String.valueOf(Math.random())).setHeader("column 1");
                grid.addColumn(string->String.valueOf(Math.random())).setHeader("column 2");
            
                grid.addColumn(string->String.valueOf(Math.random())).setHeader("column 
                   3").setKey("lastName");

           
                grid.addColumn(value -> LocalDate.now()).setHeader("date");
             
                grid.addColumn(new LocalDateRenderer<>(item -> LocalDate.now()))
                        .setHeader("LocalDateRender")
                        .setResizable(true)
                        .setSortable(true);
             

                grid.setPageSize(20);
              grid.setItems(IntStream.rangeClosed(1, 120000).mapToObj(number -> String.valueOf(number)));

                 add(grid);
                 add(new Button("Add new Column", e->{
                      grid.addColumn(new LocalDateRenderer<>(item -> LocalDate.now().plusDays(444)))
                                 .setHeader("LocalDateRender")
                                 .setResizable(true)
                                 .setSortable(true);
                 }));
        }
}
```
Clicking on column display the data

**Comment by Springrbua** [comment]
I am probably facing the same issue in an app I am working on:
I have to change the columns, based on the window width. On small screens I show different columns then on large screens.
I therefore created a listener, which gets notified on window.resize and update the columns.
The columns are updated correctly, but the content is not shown, until I trigger a refresh, for example by changing the sort.
While trying to find out whats causing the issue, I noticed, that `ComponentDataGenerator#setNodeIdPropertyName` is called **after** `ComponentDataGenerator#generateData`, causing `generateData` to return immediately, without calling `createComponent`.

I tested this with Vaadin 14.0.0.beta2

**Comment by Danuta97** [comment]
Hello! I`m using a grid to display data. When I click on a grid row it opens a dialog where im editing the selected row. When I select a value from a comboBox and press confirm to save changes the grid disappears totally. I saw that this problem appears only in Chrome browser. How can I fix this problem? (**I attached a print screen with the grid with opened dialog for editing and another one with the grid after i pressed confirm button in the dialog) 
p.s: I`m using vaadin 14.

Thanks!
![dialog](https://user-images.githubusercontent.com/44115275/66487872-bf3df680-eab5-11e9-8bbd-f74c9c8a974f.png)
![nogrid](https://user-images.githubusercontent.com/44115275/66487874-bf3df680-eab5-11e9-940b-a24291da30a8.png)

**Comment by anasmi** [comment]
Hi @Danuta97,
this isssue is closed as fixed, so it would be better if you create a new ticket on Github, if you think it's a bug in Grid. If you need help in configuration, then Forum or StackOverflow are better places, since you will get more visibility there. :)
