### ISSUE TITLE
Tabbing between component cells does not always work

### ISSUE THREAD

**Issue by drewharvey** [vaadin/vaadin-grid-flow#595]
**Vaadin Flow 13.0.1
Chrome 72.0.3626.121 (Official Build) (64-bit)**

Tabbing through components in cells is very inconsistent.  Sometimes you simply jump from one cell component to the next cell component, other times you jump from cell component to cell body.  Creating reproduction steps is difficult as the behavior does not always act the same.

The Grid I'm seeing this problem in has a List data provider and the list is dynamically manipulated (adding/removing items).  The list size starts at 0 and eventually items are added to it with user input.

**Example**
In this GIF, you can see how the focus jumps from the ComboBox component to the next cell's body (this cell contains a disabled ComboBox).  This causes the focus to never reach the Button component at the end of the grid.
![vaadin-grid-tabbing-issue](https://user-images.githubusercontent.com/2496955/54726942-7da62800-4b32-11e9-8bdf-5a5be4251df0.gif)

**Comment by pleku** [comment]
@drewharvey please provide a minimal UI sample to reproduce the issue.

**Comment by drewharvey** [comment]
I am having a hard time creating an example.  The tabbing behavior seems random in our own application, yet I have not been able to repro this outside of the application.

**Comment by tomivirkki** [comment]
Using focusable elements in the grid cells is generally problematic and should be avoided. If you reorder the columns, they're not physically reordered in the DOM (flexbox order is used instead) but tabbing still follows the tab order. Not sure if that was the case here.

Now that there is built-in grid row editor, grid pro and crud for editing grid data, this might no longer be relevant. Do reopen if still relevant but please provide more information on how to reproduce, with a code snippet preferably.
