### ISSUE TITLE
Get the Grid Column by ClickListener

### ISSUE THREAD

**Issue by ippei-akiya-takumi** [vaadin/vaadin-grid-flow#612]
Current Vaadin-grid-flow provides API for the getting a row item object by ClickListener and GridContextMenu. This API is very useful, and I suggest to add the API for getting a column item object or name into vaadin-grid-flow APIs.
This is just my suggestion, not any kind of issue report.

**Comment by pekam** [comment]
Workaround provided in https://vaadin.com/forum/thread/17585345/17586229

**Comment by pekam** [comment]
This feature will be included in `vaadin-grid-flow 4.1.0`. That version is targeted for Vaadin 14.2 (not the next minor) in order to ensure a proper pre-release/validation period for this and the other new Grid features.
