### ISSUE TITLE
Add scroll to index API

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-grid-flow#618]

**Comment by tepi** [comment]
public void scrollTo(int row)
                  throws IllegalArgumentException

    Parameters:
    row - zero based index of the item to scroll to in the current view.

    Throws:
    IllegalArgumentException - if the provided row is outside the item range



    public void scrollToStart()

    Scrolls to the beginning of the first data row.



    public void scrollToEnd()

    Scrolls to the end of the last data row.

**Comment by tepi** [comment]
PR at https://github.com/vaadin/vaadin-grid-flow/pull/778
