### ISSUE TITLE
Grid column html-side rendering.

### ISSUE THREAD

**Issue by elmot** [vaadin/vaadin-grid-flow#62]
It would be handy to use column template in .html file with data provided from server side, like here:
```html
<vaadin-grid id="someGrid">
      <vaadin-grid-column id="fancyHtmlColumn" width="..."...>
        <template class="header">...</template>
        <template>...[[value]]</template>
      </vaadin-grid-column>
</vaadin-grid>
```

And  java counterpart
```java
@Id("someGrid")
Grid<Item> grid;
...
grid.addTemplateColumn("fancyHtmlColumn", Item::getFancyData);
```
Now we can define a column at client side with html but we can not provide data for it.

**Comment by Legioth** [comment]
The same functionality would also be relevant for `ComboBox` and `IronList`.

**Comment by elmot** [comment]
The same for grid row details generator

**Comment by simonurmi** [comment]
Without this feature it's impossible to properly separate structure, style and data.

**Comment by Legioth** [comment]
This is doable today by abusing a hidden column, as described in https://github.com/vaadin/flow/issues/4221#issuecomment-394334330. We should still add proper support for this.

**Comment by gilberto-torrezan** [comment]
This was fixed by https://github.com/vaadin/vaadin-grid-flow/issues/233

**Comment by web-padawan** [comment]
Closing per above comment https://github.com/vaadin/vaadin-grid-flow/issues/62#issuecomment-438652879. Please open a new issue if needed.
