### ISSUE TITLE
Show component in column when the mouse hover the row

### ISSUE THREAD

**Issue by mdre** [vaadin/vaadin-grid-flow#625]
There no way to show component in a column only when the mouse is over the row. The way used on Gmail, for example, is the most clear way to show component associated to the row data in a grid. 
![Screenshot_20190417_073051](https://user-images.githubusercontent.com/5312780/56281500-2a98a400-60e3-11e9-9d81-51955e2e9bac.png)

**Comment by jouni** [comment]
The best workaround I can come up with at the moment is to toggle a custom CSS property when hovering over a row.

This is what would be needed in the client-side:

```html
<dom-module id="grid-row-hover" theme-for="vaadin-grid">
  <template>
    <style>
      [part~="row"]:not(:hover) {
        --hover-actions-display: none;
      }
    </style>
  </template>
</dom-module>
```

Then use that custom property for the components that you wish to hide:

```html
<style>
.hover-actions {
  display: var(--hover-actions-display, block);
}
</style>
```

The way you apply the `.hover-actions` class depends whether you do it from the server (Flow/Java) or in a client-side template (Polymer/HTML).

**Comment by jouni** [comment]
Getting the exact same behavior as shown in the screenshot (Gmail), I suspect you will need to hide the entire column which contains the actions and position it on top of the other columns.

Alternatively, you can place the actions inside the same column as the other content (the email summary and the date) as the actions flow over both of those. But that means you’ll lose separate headers for those columns.

**Comment by jouni** [comment]
I whipped up an example quickly:

- [Demo](https://grid-hover-actions.glitch.me)
- [Source](https://glitch.com/edit/#!/grid-hover-actions?path=index.html)

Note, that you should consider providing the same features for keyboard (and/or screen reader) users and touch devices somehow. Currently, those action buttons are inaccessible for non-mouse users.

**Comment by mdre** [comment]
It's a great solution. I'm trying to make it work on Flow/Java but  but I'm failing for now.

**Comment by mdre** [comment]
Well... based on the @jouni solution, I could recreate one in Flow.
First, add this to the shared-style
```
<dom-module id="grid-row-hover" theme-for="vaadin-grid">
    <template>
        <style>
            [part~="row"]:hover > [part~="body-cell"]{
                --hover-actions-display: flex;
                background-color: #b4cefe;
             }
            [part~="row"]:not(:hover) > [part~="body-cell"]{
                --hover-actions-display: none;
             }
        </style>
    </template>
</dom-module>
```
and then, you can create a CSS rule based on the ` --hover-actions-display` variable and apply it to a component.
In my case, I point to a HorizontalLayout:
```
<dom-module id="grid-div-hide" theme-for="vaadin-horizontal-layout">
    <template>
        <style>
            :host(.hoverDivHide) {
                display: var(--hover-actions-display, flex);
                position: fixed;
                top: 0;
                right: 0px;
                align-items: center;
            }
        </style>
    </template>
</dom-module>
```
after that, in the Java part of Flow you can do this: 

```
public void testGrid() {
        List<Person> personList = new ArrayList<>();
        
        personList.add(new Person("Lucas", "Washington"));
        personList.add(new Person("Peter", "New York"));
        personList.add(new Person("Samuel", "Washington"));
        personList.add(new Person("Anton", "Washington"));
        
        
        CCGrid<Person> grd = new CCGrid<>();
        grd.addColumn(Person::getNombre).setHeader("Nombre").setFlexGrow(1);
        grd.addColumn(Person::getDireccion).setHeader("Dirección").setFlexGrow(1);
        grd.addComponentColumn(per -> {            
            HorizontalLayout actions = new HorizontalLayout();
            actions.addClassName("hoverDivHide");
            
            CCButton remove = new CCButton("x");
            remove.addThemeVariants(ButtonVariant.LUMO_ERROR,ButtonVariant.LUMO_SMALL);
            remove.addClickListener((event) -> {
                
            });
            actions.add(remove);
            
            return actions;
        }).setTextAlign(ColumnTextAlign.END).setKey("controls").setFlexGrow(0).setWidth("1px");
        grd.setItems(personList);
        
        add(grd);
    }
}

class Person {
    String nombre;
    String direccion;

    public Person() {
    }

    public Person(String nombre, String direccion) {
        this.nombre = nombre;
        this.direccion = direccion;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getDireccion() {
        return direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    
}
```

An interesting thing is that I have to set the `position` attribute to `fixed` and set column with to 1 or more to make it work.
