### ISSUE TITLE
Method getId() not used when selecting rows in multi-select mode

### ISSUE THREAD

**Issue by mlopezFC** [vaadin/vaadin-grid-flow#638]
## Tested on Vaadin 13.0.6, and 13.0.3
When using `getId()` method in DataProvider, and then trying to select objects that are equals based on that method result, the result is not as expected.
Using the following code:
```
@Route("")
public class MainView extends VerticalLayout {
	public static class VO {
		private String label;
		public VO(String label) {
			this.label = label;
		}
		public String getLabel() {
			return label;
		}

		// default equals and hashcode
		
		
		@Override
		public String toString() {
			return label;
		}
//		@Override
//		public int hashCode() {
//			final int prime = 31;
//			int result = 1;
//			result = prime * result + ((label == null) ? 0 : label.hashCode());
//			return result;
//		}
//		@Override
//		public boolean equals(Object obj) {
//			if (this == obj)
//				return true;
//			if (obj == null)
//				return false;
//			if (getClass() != obj.getClass())
//				return false;
//			VO other = (VO) obj;
//			if (label == null) {
//				if (other.label != null)
//					return false;
//			} else if (!label.equals(other.label))
//				return false;
//			return true;
//		}
	}

	public MainView() {
		Grid<VO> g = new Grid<VO>();
		g.addColumn(VO::getLabel).setHeader("Label");
		g.setDataProvider(new ListDataProvider<VO>(Arrays.asList(new VO("A"), new VO("B"))) {
			@Override
			public Object getId(VO item) {
				return item.getLabel();
			}
		});
		g.setSelectionMode(Grid.SelectionMode.MULTI);
		g.select(new VO("B"));
		g.select(new VO("B"));
		g.select(new VO("B"));

		new Notification("Selected items (expected 1 as all are equal by datasource ID): " + g.getSelectedItems())
				.open();
		add(g);
	}
}
```
The result is that the returned selected items are three instead of one. Try uncommenting equals and hashCode overwritten implementations and it will work. For my understanding the equality check should be handled by the DataProvider, and Grid seems to not be doing that, instead is using equals and hashcode.

**Comment by pekam** [comment]
The problem is most likely in `AbstractGridMultiSelectionModel` class, which uses `Set::contains` to check if item is already selected ([on this line](https://github.com/vaadin/vaadin-grid-flow/blob/5db69b600f45271ad5ed84dcc70e5417ebb96743/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModel.java#L194)).

There might be other problems in that class (or elsewhere) as well, as it seems to mostly just use `Set` operations without caring about the ids.
