### ISSUE TITLE
Reconsider Column implementing HasStyle

### ISSUE THREAD

**Issue by pekam** [vaadin/vaadin-grid-flow#65]
Currently `Column` implements `HasStyle`, but adding CSS for the element doesn't seem to have any effect on the columns.
Recently a developer used `column.addClassName()` because such API exists there, but this did nothing for the UI. This is just confusing.
Is there any reason for having this API, or could it be removed?
Setters and getters for `width` and `flex-grow` are implemented in the `Column` class.

**Comment by gilberto-torrezan** [comment]
The main reason for columns to implement `HasStyle` is to allow them to be selected by CSS rules defined outside (in an external CSS file for example).

Hypothetical use case: "I want the first column of the Grid to have a green background color".

**Comment by pleku** [comment]
>Recently a developer used column.addClassName() because such API exists there, but this did nothing for the UI.

If the class name doesn't go the DOM, then it is a bug. Does this happen or not ?

**Comment by pekam** [comment]
If I remember correctly the class name goes to the element but that is not the point.

`<vaadin-grid-column>` is not a visual element, it's just used for configuring the grid. Adding styles to the element doesn't magically transport these styles to the grid cells, that are not children of the column.

**Comment by pekam** [comment]
The issue isn't that the styles wouldn't go to the `<vaadin-grid-column>`. The issue is that it's confusing to provide this API as it doesn't affect anything and the users expect all the cells in that column to be styled.

**Comment by pleku** [comment]
Right, the `Column` could instead have `HasClassName` but not `HasStyle`.

**Comment by pleku** [comment]
And now it feels a bit weird that `HasStyle` applies both, instead of just the  `Style getStyle()` API.

**Comment by pleku** [comment]
Neither makes sense for `Column`, so let's just remove `HasStyle`.
