### ISSUE TITLE
Add deep refreshItem method to hierarchical data provider 

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/vaadin-grid-flow#651]
Changes in the structure of a tree grid node are not recognized by the data providers's refreshItem method, when the item is expanded and it's children are shown.

This includes:
- adding a child to a node with existing (and expanded) child nodes
- removing a child from a node with expanded child nodes

The refresh item works on:
- adding/removed a child to/from a node, that has not been expanded yet

I guess this is somehow related to the lazy loading mechanism (I used the AbstractBackEndHierarchicalDataProvider).

The disadvantage of this is, that tree modifications always require a refreshAll, even if there is only a slightly modification in a deep level of the tree. 

Request is to add a method `refreshItem(T item, boolean deep)`, that rebuilds the structure of the given item, when deep is `true` (as refreshAll is doing now for the whole structure).

`refreshItem(T item)` would behave as it does now (i.e. calling `refreshItem(item, false)` )

Used versions are V14, beta1, grid-flow 3.1-SNAPSHOT

**Comment by AdamBrowning** [comment]
This is a pretty huge issue for us. All over our application, we have small changes to order/add/remove of children and calling `refreshAll` is very heavy-handed and disorienting to the user.

**Comment by pekam** [comment]
The description proposes a new feature `refreshItem(T item, boolean deep)`, so it seems that this shouldn't be labeled as a bug and thus is not a valid issue to vote as a BFP.

But if the functionality of `refreshItem(T item)` is considered broken, and that it should behave like `refreshAll()` but only for the children of this particular item, that's a different case.

Personally I think that `refreshItem(T item)` works as it should, and this should be a new feature like suggested.

**Comment by pleku** [comment]
I looked up that `refreshItem` works as it has before in Framework 8, so the current behavior is not in any way "accidental" or regression. And as it is clearly a suggestion to add _new API_, this should be also labeled as an enhancement instead of a bug, to avoid confusion.

**Comment by wfischlein** [comment]
Steps to reproduce:
- create a page that has a TreeGrid with one rootnode that has at least one subnode
(or just modify `com.vaadin.flow.component.treegrid.it.TreeGridChangingHierarchyPage` accordingly) 
- provide code that can add another subnode
- expand rootnode (in browser)
- Either call `grid.getDataProvider().refreshItem(rootnode)` -> Found: the new subnode does not get displayed
- or call `grid.getDataProvider().refreshAll()` -> Found: the whole tree gets reloaded
Expected: have a method `DataProvider.refreshItem(T item, boolean deep)`, call that and see that only the subnodes of rootnode get redisplayed in the browser

I spent almost two days to find that calling
`dataController.setResendEntireRange(true);`
`requestFlush(dataController);`
helps to exactly refresh the item where `dataController` is responsible for plus the subitems. So this should be done in case of a `refreshItem(T item, boolean deep)`.
Unfortunately when you now close and reopen the rootnode and then add another child node right away it still does not get displayed. After another two+ days I give up now to try to fix that. The only difference I could burn it down to (close rootnode, call refreshAll(), open rootnode, add another child versus close rootnode, open rootnode, add another child) is that in the first (working) case the browser sends two requests on adding the child. The second one produces 

> for(;;);[{"syncId":10,"clientId":10}]

 as a response whereas the second (non-working) case that request does not happen.

**Comment by TatuLund** [comment]
I think this issues should be closed by https://github.com/vaadin/flow/pull/6202
