### ISSUE TITLE
Selection column width should adapt to width of checkbox

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-grid-flow#660]
Currently the `vaadin-grid-flow-selection-column` has a hardcoded width of `58px`:

https://github.com/vaadin/vaadin-grid-flow/blob/9d9406293526dd0e497b49f5b6b4186e9c6a3d2f/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/vaadin-grid-flow-selection-column.html#L37-L40

This can be too wide and I couldn't find a way to override this. Now that `vaadin-grid-column` has the `autoWidth` property, it would be great to be the default and also let the developer get an instance of the selection column and set the desired width.

**Comment by heruan** [comment]
Another useful use case of having the selection column exposed would be to be able to hide it or move it, like other columns.

**Comment by tomivirkki** [comment]
Workaround:
```java
grid.getElement().executeJs("this.querySelector('vaadin-grid-flow-selection-column').width='1000px'");
```

**Comment by rolfsmeds** [comment]
Even more severe than the col being too wide is that, given a large enough checkbox, it can easily be too narrow, causing overflow ellipsis to appear etc. So I'd say regardless of whether the API gives access to it or not, that hardcoded width needs to be addressed.
