### ISSUE TITLE
Binder throws Exception with Grid Editor and Bean Level Validator

### ISSUE THREAD

**Issue by tboehm-xdev** [vaadin/vaadin-grid-flow#690]
Tested with: Vaadin 14.0.0.beta3

i added an bean level validator to my binder. 
`binder.withValidator(new MyValidator());`

The binder is used in an Grid Editor.
(`grid.getEditor().setBinder()`)

in the Editor i have an 'Save' button which calles.
`editor.save();`

When i press now save, following Exception throws

> ERROR [com.vaadin.flow.server.DefaultErrorHandler] (default task-94) : java.lang.IllegalStateException: Cannot validate binder: bean level validators have been configured but no bean is currently set
	at com.vaadin.flow.data.binder.Binder.validate(Binder.java:1986)
	at com.vaadin.flow.data.binder.Binder.validate(Binder.java:1970)

if i remove the bean level validator, everything is fine.

**Comment by pekam** [comment]
Hi! I couldn't reproduce the issue, using Vaadin 14.0.0.rc2. Here's my code:

```java
Grid<Person> grid = new Grid<>();
grid.setItems(new Person("foo"), new Person("bar"));
Column<Person> nameCol = grid.addColumn(Person::getName);
Column<Person> saveCol = grid.addColumn(item -> "save");
Editor<Person> editor = grid.getEditor();
grid.addItemClickListener(e -> editor.editItem(e.getItem()));
add(grid);

TextField textField = new TextField();
nameCol.setEditorComponent(textField);

Button saveButton = new Button("save");
saveButton.addClickListener(e -> {
    editor.save();
});
saveCol.setEditorComponent(saveButton);

Binder<Person> binder = new Binder<Person>().withValidator(
        person -> person.getName().length() > 2, "too short name");
binder.forField(textField).bind(Person::getName, Person::setName);
editor.setBinder(binder);
```

Maybe I've missed something? Could you provide a minimal code example which reproduces the problem?

**Comment by tboehm-xdev** [comment]
i will create an minimal example project in the next few days

**Comment by tomivirkki** [comment]
Closing as inactive
