### ISSUE TITLE
Please can I have expandAll()

### ISSUE THREAD

**Issue by enver-haase** [vaadin/vaadin-grid-flow#691]
See
https://vaadin.com/forum/thread/16990453/16990506

as history repeats :D

**Comment by enver-haase** [comment]
expand(Collection collection) maps onto expand(collection, userOriginated = false)
should it not be "true"?

**Comment by enver-haase** [comment]
I have one example where
expandRecursively(Collections.singleton(root), Integer.MAX_VALUE);
works and one where it does not work at all.
I am somewhat puzzled.

**Comment by web-padawan** [comment]
The `expandAll` API is also requested at #771 so let me close this one as a duplicate.
