### ISSUE TITLE
Uncaught TypeError: Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by nickarmb** [vaadin/vaadin-grid-flow#694]
I´m trying to fix a bug with a vaadin autocomplete component. I added the component to a simple view. So if i put some text input the autocomplete text field and move to another view and then go back to the view with the filled component, the error message "Uncaught TypeError: Cannot read property 'style' of undefined" drops in browser. If the textfield of the autocomplete is empty, i can switch the views normally without an error. To catch data for the autocomplete, i use a spring bean. To handel the data i use the @UIScope from spring

![Unbenannt](https://user-images.githubusercontent.com/52233781/60158906-4eb6e680-97f2-11e9-9052-e42d0353ddf3.PNG)

**Comment by web-padawan** [comment]
It's a wrong repo so I'm closing the issue.

Please open a new issue at https://github.com/vaadin-component-factory/vcf-autocomplete
