### ISSUE TITLE
TreeGrid with details is unreliable in Chrome, a little less in Safari, less but still unreliable in Firefox

### ISSUE THREAD

**Issue by enver-haase** [vaadin/vaadin-grid-flow#701]
This relates to #563, #525 .

I have a hard time describing what the TreeGrid actually does but it does not do things right when it comes to details rows.

It seems to work fine in Firefox until I collapse the root for the first time.

In Safari, I see mostly empty details rows -- but not only.

Can you please check out the code at
https://github.com/enver-haase/Playground/tree/master/summarizing-tree
(very simple TreeGrid) and see yourself?

I am happy to provide an online demonstration.

**Comment by enver-haase** [comment]
Oh, used Vaadin 14.0.0.rc3

**Comment by jcgueriaud1** [comment]
Hi,

In your example, there is 2 bugs:
* the #525 bug (the item detail is not rendered correctly the first time)
* when you collapse a node then:
** item details is not shown (but everything is processed correctly)

But thanks for your code, it's easy to reproduce the wrong behaviour.

**Comment by jcgueriaud1** [comment]
Closed by #732
