### ISSUE TITLE
Click on multi-select check box in grid triggers ItemClickEvent

### ISSUE THREAD

**Issue by steffen-harbich-itc** [vaadin/vaadin-grid-flow#702]
Since Vaadin 14 rc3, the item click listener is also triggered when you click on the check box for multi select of grid items. But this is a problem for my use case because I want to select grid items via the item click event:

```
categories.setSelectionMode(Grid.SelectionMode.MULTI);
categories.addItemClickListener(event -> {
            if (categories.getSelectionModel().isSelected(event.getItem())) {
                categories.deselect(event.getItem());
            }
            else {
                categories.select(event.getItem());
            }
        });
```

Until Vaadin 14 rc2 it worked fine. So, I wonder why this behavior was changed.
I am using FF latest, gradle, Spring Boot.

**Comment by pekam** [comment]
Thanks for reporting! This seems to be an unwanted side-effect of refactoring #608 and it should be fixed.

Technical details:
Previously, the `ItemClickEvent` used the web component's `cell-activate` event to find the target item. Now it uses the web component's `getEventContext` function to get the target item from the `click` event. The difference is that the `cell-activate` event is not fired on the grid when clicking the checkbox, but `click` event is. [Based on the `cell-activate` functionality](https://github.com/vaadin/vaadin-grid/blob/f6efd4ea2c331a40451d25667527cf7488e2403e/src/vaadin-grid-active-item-mixin.html#L66), the event didn't fire for any focusable components in grid, but now it does (e.g. when clicking a button inside grid). To avoid duplicating the logic from the web component's `cell-activate` implementation, the best way to fix it would probably be to fire `ItemClickEvent` only when there was a `cell-activate` event as well.
