### ISSUE TITLE
Grid row details does not work if grid is defined in html but DetailGenerator is set with Java.

### ISSUE THREAD

**Issue by elmot** [vaadin/vaadin-grid-flow#71]
Looks like quite fundamental problem with templates being set on-the fly.
Steps to reproduce:

Checkout branch `broken-grid-details-if-template` Patient Portal for Flow,  build and run it. 
Open any user journal, click any row -> nothing happens, whereas details generator is defined.

Related to vaadin/vaadin-grid#1196

**Comment by pleku** [comment]
This is a known limitation, no plans to support it currently.

**Comment by gilberto-torrezan** [comment]
This is probably related to https://github.com/vaadin/flow/issues/3513
