### ISSUE TITLE
setDeselectAllowed(false) does not work as expected

### ISSUE THREAD

**Issue by markhm** [vaadin/vaadin-grid-flow#713]
Using vaadin.version 14.0.0.rc4, I am not seeing the expected behaviour when disallowing deselection of a grid item. 

```
    grid = new Grid<>(Person.class, false);
    grid.setItems(getData(..));

    grid.setSelectionMode(Grid.SelectionMode.SINGLE);

    // does not work as expected
    ((GridSingleSelectionModel) grid.getSelectionModel()).setDeselectAllowed(false);
```

Expected behaviour: Not being able to unselect a (pre-selected) grid item, disallowing zero selected items on the grid.

Actual behaviour: Still being able to deselect (and select again) a grid item.

**Comment by sirbris** [comment]
For TreeGrid setDeselectAllowed(false) works on the server side but on the client side it still seems to be deselected
`((GridSingleSelectionModel<T>) getSelectionModel()).setDeselectAllowed(inDeselectAllowed);`
Or am I missing something? I'm using Vaadin 14.2.2
