### ISSUE TITLE
Calling setSelectionMode-multiple times causes multiple selection checkboxes

### ISSUE THREAD

**Issue by petrixh** [vaadin/vaadin-grid-flow#721]
When calling setSelectionMode(MULTI) several times, the grid ends up with multiple selection checkboxes. And if you additionally enable setColumnReorderingAllowed(true) you can move them around... 

Minimal reproduceable example: 

` public class MainView extends VerticalLayout {

	public MainView() {

		Grid<MessageBean> messageBeanGrid = new Grid<>(MessageBean.class);
		messageBeanGrid.setItems(createMessages());

		add(messageBeanGrid);

		messageBeanGrid.setSelectionMode(SelectionMode.MULTI);
		messageBeanGrid.setSelectionMode(SelectionMode.MULTI);
		messageBeanGrid.setSelectionMode(SelectionMode.MULTI);
		messageBeanGrid.setSelectionMode(SelectionMode.MULTI);
		messageBeanGrid.setSelectionMode(SelectionMode.MULTI);
		messageBeanGrid.setSelectionMode(SelectionMode.MULTI);
		messageBeanGrid.setSelectionMode(SelectionMode.MULTI);

		messageBeanGrid.setColumnReorderingAllowed(true);
	}

	private List<MessageBean> createMessages() {
		return IntStream.range(0, 10).mapToObj(i -> new MessageBean()).collect(Collectors.toList());
	}

	public class MessageBean {

		private String message;
		private String time;

		public String getMessage() {
			return "Button was clicked at " + LocalTime.now() + message;
		}

		public void setMessage(String message) {
			this.message = message;
		}

		public String getTime() {
			return time;
		}

		public void setTime(String time) {
			this.time = time;
		}
	}

}
`

Tested with: 
Vaadin Platform 14.0.0.rc6 (observed in bower mode but seems to be present in NPM mode as well) 
Java:8
OS X 10.14
Chrome (latest evergreen at the time of writing the ticket)

![Screenshot 2019-07-25 at 13 32 20](https://user-images.githubusercontent.com/3215653/61867806-ad01e280-aee0-11e9-9ccb-3f850dd4f5f0.png)

**Comment by jcgueriaud1** [comment]
I've tried the example in Vaadin 14.1.27 and it's fixed.

**Comment by tomivirkki** [comment]
Thanks @jcgueriaud1, closing
