### ISSUE TITLE
Missing API for listening to column resize

### ISSUE THREAD

**Issue by petrixh** [vaadin/vaadin-grid-flow#722]
While it seems to be possible to make columns resizable, through Column.setResizable() it doesn't seem to be possible to listen to column resize events from the server-side API

Tested on: 
Vaadin Platform: 14.0.0.rc6

**Comment by pleku** [comment]
Depends on https://github.com/vaadin/vaadin-grid/issues/1538

**Comment by tomivirkki** [comment]
Closed by https://github.com/vaadin/vaadin-grid-flow/pull/746
