### ISSUE TITLE
Add convenience methods for node expansion in Tree

### ISSUE THREAD

**Issue by edler-san** [vaadin/vaadin-grid-flow#738]
Often a user wants to expand an item that is rather deep in a given tree. As of now he has to programmatically traverse upwards from the node and expand every node to the root to ensure it is visible. Add a convenience method for that, say `expand(Node n, boolean expandParents)`.

Alternatively provide an API similar to SWT's `showItem(TreeNode node)` for which the doc states "Shows the item. If the item is already showing in the receiver, this method simply returns. Otherwise, the items are scrolled and expanded until the item is visible." This relates to https://github.com/vaadin/vaadin-grid-flow/issues/327 as well.

**Comment by enver-haase** [comment]
See #691

**Comment by web-padawan** [comment]
Closing in favor of #772.
