### ISSUE TITLE
Grid forgets to render some rows in 1M items dataset

### ISSUE THREAD

**Issue by VGoudkov** [vaadin/vaadin-grid-flow#741]
- Description of the bug
When scrolling simple grid with 1M rows some rows render as empty lines
- Minimal reproducible example
```
@Route("")
@PWA(name = "Project Base for Vaadin", shortName = "Project Base")
public class MainView extends VerticalLayout {
    public MainView() {
        Grid<Data> grid = new Grid<>();
        grid.addColumn(Data::getId).setHeader("Id");
        grid.addColumn(Data::getName).setHeader("Name");
        final int rows = 1_000_000;
        List<Data> items = new ArrayList<>(rows);
        for (int i = 0; i < rows; i++) {
            items.add(new Data(i, String.format("Item: %d", i)));
        }
        grid.setItems(items);
        add(grid);
    }

    public class Data {
        final int id;
        final String name;
        public Data(int id, String name) {
            this.id = id;
            this.name = name;
        }
        public int getId() {
            return id;
        }
        public String getName() {
            return name;
        }
    }
}
```
- Expected behavior
Smooth scroll all rows by mouse, may be some delays
- Actual behavior
Some rows are rendered as blank lines (sometimes all visible rows)
- Versions:
    - Vaadin / Flow version ```14.0.0```
    - Java version ```11.0.4 AdoptJDK```
    - OS version ```Win10 x64```
    - Browser version (if applicable) ```Chrome 76.0.3809.100```

**Comment by tomivirkki** [comment]
Confirmed, looks like the empty rows are stuck in `loading` state for some reason. A quick workaround could be to unhide the content on `loading` rows with a style module with the following addition:

```
[part~="row"][loading] [part~="body-cell"] ::slotted(vaadin-grid-cell-content) {
  opacity: 1;
}
```
...but this clearly needs a proper fix to the connector. On some occasions the grid is stuck in a state where it continuously keeps requesting data from the server and sometimes there's no requests but the rows are still marked `loading`.
