### ISSUE TITLE
Bug: Reattaching a Grid resets its sort order

### ISSUE THREAD

**Issue by gsedlacz** [vaadin/vaadin-grid-flow#747]
**Vaadin Version**
14.0.2

**Problem**
If you have a Grid with a surrounding layout and you reattach the Grid it loses its sort order.
To be more precise it overrwrites it with an empty one.

The example code below logs changes to the sort order.

**Example**
As an example i pressed the first, second, third and second columns header.
The log result looks like this:

    1
    2
    3
    3

![image](https://user-images.githubusercontent.com/33100708/63509804-5d153c00-c4dd-11e9-8eec-7de4d81538ec.png)

If you press the "rm" button and then the "attach" button `0` gets added to the log and after a short moment the grid loses its sort order.

**Example code**

    @Route("test")
    public class TEST extends FlexLayout {
        private TEST_GUI gui;
    
        public TEST() {
            setSizeFull();
        
            gui = new TEST_GUI();
        
            Button btRm = new Button("rm", evt -> remove(gui));
        
            Button btattach = new Button("attach", evt -> add(gui));
        
            add(btRm, btattach, gui);
        }
    
        private List<TEST_DATA> createTestData() {
            List<TEST_DATA> data = new ArrayList<>();
        
            for(int i=0; i<999; i++) {
                data.add(new TEST_DATA("test" + i, i, (int)(Math.random() * 100)));
            }
        
            return data;
        }
    
        public class TEST_GUI extends FlexLayout {
            public TEST_GUI() {
                setSizeFull();
            
                Grid<TEST_DATA> grid = new Grid<>(TEST_DATA.class);
                grid.setSizeFull();
            
                grid.setItems(createTestData());
                // removes generated columns
                grid.removeAllColumns();
            
                grid.addColumn(TEST_DATA::getStest).setSortable(true).setHeader("String");
                grid.addColumn(TEST_DATA::getSint).setSortable(true).setHeader("index");
                grid.addColumn(TEST_DATA::getRandom).setSortable(true).setHeader("random");
            
                grid.setMultiSort(true);
                grid.setSelectionMode(SelectionMode.MULTI);
            
                grid.addSortListener(e -> {
                    System.out.println(e.getSortOrder().size());
                });
                
                add(grid);
            }
        }
    
        public class TEST_DATA {
            public String stest;
            public int sint;
            public int random;
        
            public TEST_DATA(String stest, int sint, int random) {
                super();
                this.stest = stest;
                this.sint = sint;
                this.random = random;
            }
            public String getStest() {
                return stest;
            }
            public void setStest(String stest) {
                this.stest = stest;
            }
            public int getSint() {
                return sint;
            }
            public void setSint(int sint) {
                this.sint = sint;
            }
            public int getRandom() {
                return random;
            }
            public void setRandom(int random) {
                this.random = random;
            }
        }
    }

**Comment by hangorn** [comment]
Same problem: we have a grid inside a tab content, and when you come back to this tab, the grid does not keep its sort order.
