### ISSUE TITLE
Missing feature to define grid height

### ISSUE THREAD

**Issue by 35niavlys** [vaadin/vaadin-grid-flow#752]
Between setHeightByRows(boolean), setHeight and setMaxHeight, we cannot define the maximum number of rows to display.

In fact, I was expecting `setHeightByRows(int maxRows)`

**Comment by tomivirkki** [comment]
Grid in V10+ has dynamic row height, meaning that height of each rows is defined by the content that takes the most vertical space on it and this can be different for each row. If you know the height of the grid rows in your app are always the same, you can assign an explicit pixel height for the grid.
