### ISSUE TITLE
IT tests fail because of client side exception

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/vaadin-grid-flow#761]
All It test has a client side exception in console

```
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "vaadin-text-field" has already been used with this registry
    at Module.<anonymous> (http://localhost:9998/VAADIN/build/vaadin-bundle-d094be56a3e2a2d21b61.cache.js:2372:189)
    at i (http://localhost:9998/VAADIN/build/vaadin-bundle-d094be56a3e2a2d21b61.cache.js:1:110)
    at http://localhost:9998/VAADIN/build/vaadin-bundle-d094be56a3e2a2d21b61.cache.js:1:902
    at http://localhost:9998/VAADIN/build/vaadin-bundle-d094be56a3e2a2d21b61.cache.js:1:912
```

Those tests that have a check that there is no exceptions are failing.

It happens because `grid-flow` depends on `vaadin-text-field` `2.4.7` version.
But `grid-flow-demo` module depends on `vaadin-text-field-flow`   which depends on `2.4.11`.

**Comment by denis-anisimov** [comment]
The issue is still valid even though I've fixed the version in the main `grid-flow` module.
Looks like the versions are different again.

**Comment by web-padawan** [comment]
This should not be the case now. Closing.
