### ISSUE TITLE
Rendered components in TreeGrid disappear when a node is collapsed

### ISSUE THREAD

**Issue by javier-godoy** [vaadin/vaadin-grid-flow#787]
**Steps to reproduce.** 
In the attached [example](https://github.com/vaadin/vaadin-grid-flow/files/3709274/example.zip):

1. Expand "Product development"
1. Expand "Flow"
1. Collapse "Flow"
1. Select "Design"

**Observed behavior:**
The labels for "HR" and "Marketing" disappear.
![image](https://user-images.githubusercontent.com/11554739/66517154-fcf04e80-eab8-11e9-918e-3058e2bc7d59.png)

**Expected behavior:**
The labels for "HR" and "Marketing" should be visible.

**Comment by dg0s** [comment]
I'm experiencing the same issue since Vaadin 13 when using addComponentColumn with Icon component.

![bug](https://user-images.githubusercontent.com/2262980/67037919-5ccca200-f116-11e9-992c-06e3a0322a89.gif)
