### ISSUE TITLE
Unsortable Column

### ISSUE THREAD

**Issue by allenvpn312** [vaadin/vaadin-grid-flow#791]
When applying ComponentRenderer to a grid column the column becomes unsortable.  Is there a workaround for this?

Thanks

**Comment by Legioth** [comment]
For a column using a component renderer, Grid doesn't by itself know what data the column uses and can thus not know how to sort it. You can instead explicitly configure how a column should be sorted by using the `setComparator` method for in-memory data or the `setSortProperty` for backend sorting.

**Comment by allenvpn312** [comment]
Got it and thank you for your response.  It works per your recommendation.
