### ISSUE TITLE
TreeGrid partial refresh

### ISSUE THREAD

**Issue by mvysny** [vaadin/vaadin-grid-flow#792]
When calling `getDataProvider().refreshAll()`, the TreeGrid refreshes only some of the items.

Vaadin 14.0.9 in npm mode.

**Comment by mvysny** [comment]
See the attached example project which demonstrates the issue.

1. Expand the "group stuff" node.
2. Click the button.

Expected: both nodes (group and leaf) should change the caption
Actual: only the root node text is refreshed, the leaf node never changes the caption.

**Comment by mvysny** [comment]
[skeleton-starter-flow.zip](https://github.com/vaadin/vaadin-grid-flow/files/3734290/skeleton-starter-flow.zip)

**Comment by yuriy-fix** [comment]
Should be fixed by https://github.com/vaadin/flow/pull/7048
