### ISSUE TITLE
Select text in a grid row after having opened the context menu

### ISSUE THREAD

**Issue by lucienbanholzer** [vaadin/vaadin-grid-flow#794]
Dear support,

On a freshly displayed tree grid I am able to select the text in a row but after having opened a context menu by right clicking the row I am not able to select the text anymore.

Code sample : 
![select_text_grid_bug](https://user-images.githubusercontent.com/24808446/67088098-964bee80-f1a4-11e9-8352-726868a160fe.png)

Expecting :
![select_text_grid_bug_1](https://user-images.githubusercontent.com/24808446/67088025-6c92c780-f1a4-11e9-9846-a633edaefa68.png)

Best regards and thank you for your help.

**Comment by lucienbanholzer** [comment]
Hi again,

The issue can also be noted on Context Menu demo page : https://vaadin.com/components/vaadin-context-menu/java-examples.

BR

**Comment by yuriy-fix** [comment]
Closed via https://github.com/vaadin/vaadin-context-menu/pull/257
