### ISSUE TITLE
Grid column setFlexGrow is not working before grid is displayed

### ISSUE THREAD

**Issue by pekam** [vaadin/vaadin-grid-flow#8]
@alexberazouski commented on [Mon Nov 20 2017](https://github.com/vaadin/flow/issues/2978)

When grid is attached via @Id then I can't configure columns (setFlexGrow, setWidth).

But after grid was displayed, if I do column setFlexGrow on grid selection, it works.
This can be checked (check last small commit):
https://github.com/alexberazouski/skeleton-starter-flow/tree/bug/grid-set-flex-grow

grid: 4.1.0.alpha3 (alpha2 as well); flow: 1.0.0.alpha10

Note: previously we used workaround for another flow bug, so we created Grid object on server and put it into slot. Then .setFlexGrow works as expected.

**Comment by ZheSun88** [comment]
tested with vaadin-grid-flow `1.0.0.alpha7` on skeleton-starter-flow (based on platform `alpha16`) the issue is still there.

`setFlexGrow` can be used to a grid without inside a polymer template, but don't work when attach grid to template via `@id`. 

tested with other component (a button inside a button) in a template and properties (height, Id) can be set properly..

**Comment by johannesh2** [comment]
We are currently using a workaround

```
grid.getElement().addEventListener("animationend", e -> productNameColumn.setFlexGrow(10));
```

**Comment by gilberto-torrezan** [comment]
@alexberazouski the branch showcasing the problem doesn't exist anymore. I couldn't reproduce the bug - I've created the PR https://github.com/vaadin/vaadin-grid-flow/pull/100 with a test with a Grid injected by `@Id`, and everything works as expected.

Please test it out with the latest flow and let us know if the bug still persists or if there's something missing in the test.

**Comment by alexberazouski** [comment]
@gilberto-torrezan hi, I can confirm that with the flow alpha21 it works well now
