### ISSUE TITLE
"(TypeError) : Cannot set property 'size' of null" when navigating away from a view if grid lazy loading is in progress

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-grid-flow#82]
Navigating away from a view that has a Grid with a data provider sometimes causes a JS error in the browser: `(TypeError) : Cannot set property 'size' of null`. Alpha 16 of the Vaadin Platform 10 (vaadin-grid-flow 1.0.0.alpha9)

The browser console points to the `window.gridConnector.initLazy()` method:
<img width="1197" alt="image" src="https://user-images.githubusercontent.com/22416150/35916702-f600cac6-0c13-11e8-8365-4f26a34eec4e.png">

Screencast:
![screen recording 2018-02-07 at 02 26 pm](https://user-images.githubusercontent.com/22416150/35916726-115205a6-0c14-11e8-8a89-5cd76c78d6b9.gif)

In the server logs there are errors as well:
```
[qtp364266169-18] INFO com.vaadin.flow.server.DefaultDeploymentConfiguration - Will use webcomponents-loader.js polyfill discovered in webjars/webcomponentsjs
[qtp364266169-17] WARN com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler - Got an RPC for non-existent node: 9
[qtp364266169-15] WARN com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler - Got an RPC for non-existent node: 30
[qtp364266169-15] WARN com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler - Got an RPC for non-existent node: 30
[qtp364266169-15] WARN com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler - Got an RPC for non-existent node: 30
[qtp364266169-15] WARN com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler - Got an RPC for non-existent node: 30
[qtp364266169-15] WARN com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler - Got an RPC for non-existent node: 30
[qtp364266169-19] WARN com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler - Got an RPC for non-existent node: 51
[qtp364266169-19] WARN com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler - Got an RPC for non-existent node: 51
[qtp364266169-19] WARN com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler - Got an RPC for non-existent node: 51
[qtp364266169-23] WARN com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler - Got an RPC for non-existent node: 51
...
```

A demo project is attached: 
[platform16-grid.zip](https://github.com/vaadin/vaadin-grid-flow/files/1703058/platform16-grid.zip)

**Comment by caalador** [comment]
I can give a quick not on this example that the grid height is HUGE e.g. no limit and it does a request for a range of 0-1000 items so it's not lazy at all.

It does start with the normal give me 100 items, but as it calculates the size which I get as 1073x16056 it want more items.

**Comment by caalador** [comment]
Giving the VerticalLayout a height of 100% restricts the height of the Grid also and to get a `Got an RPC for non-existent node` requires fast clicking, But I couldn't see any exception in the logs.

**Comment by caalador** [comment]
Also having grid as width 100% makes things not break in the described way.

**Comment by pleku** [comment]
We have an issue with the default sizes for our components inside the ordered layouts: https://github.com/vaadin/vaadin-grid-flow/issues/11

@jouni As the Java users would expect that just using `new VerticalLayout(myGrid);` should just work without any specific sizing, what is the defaults we should have for the components/layouts ? 
I think these should also work out-of-the-box already with just the elements. Is it not so @tomivirkki ?

**Comment by jouni** [comment]
For the layouts and sizing, we have https://github.com/vaadin/vaadin-grid/issues/1202 which should be fixed.

Then we have https://github.com/vaadin/vaadin-grid/issues/1203 which only affects older Safari, and could be fixed if needed.

**Comment by pleku** [comment]
@gilberto-torrezan can this be closed now ?

**Comment by gilberto-torrezan** [comment]
This bug was fixed by https://github.com/vaadin/vaadin-grid-flow/pull/105 . Closing it.
