### ISSUE TITLE
Column reorder listener blows if the grid is in multiselect mode

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin/vaadin-grid-flow#820]
In Vaadin 14.1.beta1, I added a addColumnReorderListener on a grid with SelectionMode.MULTI.

I've got this stacktrace after I reordered one column from the client side: 
`
Caused by: java.lang.ClassCastException: elemental.json.impl.JreJsonNull cannot be cast to elemental.json.JsonString
	at elemental.json.impl.JreJsonArray.getString(JreJsonArray.java:108)
	at com.vaadin.flow.component.grid.ColumnReorderEvent.getSortedByIds(ColumnReorderEvent.java:95)
	at com.vaadin.flow.component.grid.ColumnReorderEvent.<init>(ColumnReorderEvent.java:61)`

I think it's caused because the columnsIDs (from "event.detail.columns") contains a JreJsonNull (the column for selection).

**Comment by tomivirkki** [comment]
Does your grid include hidden columns? Do the hidden column elements have a `_flowId` property? This issue would occur if it's missing.

**Comment by jcgueriaud1** [comment]
Here an example to reproduce the error. I don't think it's related to hidden columns:

`

  public class GridView extends VerticalLayout {

    private Grid<Person> multiSelectGrid = new Grid<>(Person.class);

    private Grid<Person> noneSelectGrid = new Grid<>(Person.class);

    public GridView() {

        multiSelectGrid.setSelectionMode(Grid.SelectionMode.MULTI);
        multiSelectGrid.addColumnReorderListener(personColumnReorderEvent -> {
            Notification.show("multiSelectGrid columns reordered");
        });
        multiSelectGrid.setColumnReorderingAllowed(true);
        add(multiSelectGrid);

        noneSelectGrid.setSelectionMode(Grid.SelectionMode.NONE);
        noneSelectGrid.addColumnReorderListener(personColumnReorderEvent -> {
            Notification.show("noneSelectGrid columns reordered");
        });
        noneSelectGrid.setColumnReorderingAllowed(true);
        add(noneSelectGrid);
    }

    public static class Person {
        private String name;

        public String getFirstName() {
            return firstName;
        }

        public void setFirstName(String firstName) {
            this.firstName = firstName;
        }

        private String firstName;

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }
    }
  }

`

**Comment by jcgueriaud1** [comment]
I don't know if it's related, but you can drag and drop the column for selection, which feels weird. (probably more related to vaadin-grid)

**Comment by jcgueriaud1** [comment]
@tomivirkki  Can you reproduce it ?

**Comment by tomivirkki** [comment]
Ah, yes. It's caused by the `<vaadin-grid-flow-selection-column>` which isn't added by the user and thus doesn't have a column id. It should be excluded from the reorder event completely.

**Comment by jcgueriaud1** [comment]
Ok 👍
