### ISSUE TITLE
Editor not persisting changes when using AbstractCompositeField

### ISSUE THREAD

**Issue by mlopezFC** [vaadin/vaadin-grid-flow#822]
## Description of the bug

When configuring grid editor's binder to use a custom field built based on `AbstractCompositeField`, changes are not persisted to the underlying bean.

## Minimal reproducible example

Minimal code for reproducing the issue can be found on this file: 
[binderproblem.zip](https://github.com/vaadin/vaadin-grid-flow/files/3832607/binderproblem.zip)
The example is built using buffered mode, but the same thing happens in unbuffered mode.

## Expected behavior

After editing a row, changes in the column "[column1]" should be persisted in the bean, as it happens in "[column2]" that is configured with TextField.

## Actual behavior

After editing a row, changes in the column "[column1]" are not persisted in the bean, as it happens in "[column2]" that is configured with TextField.

### Vaadin / Flow version
Tested in 14.0.12
### Java version
Java 8

**Comment by DiegoCardoso** [comment]
Hello, @mlopezFC 

It doesn't look like an issue with the Grid Editor.

At the `Picker` class, it's missing the way that the `AbstractCompositeField` gets notified about the changes of the field value. [As described here](https://vaadin.com/docs/v14/flow/binding-data/tutorial-flow-field.html#creating-fields-from-other-fields), that can be done by calling `AbstractCompositeField#setModelValue(newModelValue, fromClient)`, and by doing that, `Binder` will be able to get the right value when `Editor#save()` is called.

**Comment by mlopezFC** [comment]
Thanks Diego, you're right, I added this line in the constructor and it's working:
`textField.addValueChangeListener(ev->setModelValue(ev.getValue(), true));`
You can close this out.

**Comment by DiegoCardoso** [comment]
Glad to know it worked!
