### ISSUE TITLE
TreeGrid with HierarchyColumn is not serializable

### ISSUE THREAD

**Issue by mas4ivv** [vaadin/vaadin-grid-flow#839]
When adding a hierarchy column to a TreeGrid, it is no longer serializable. Simple test case:

    @Test
    public void serializeTreeGrid() throws IOException {
        TreeGrid<String> grid = new TreeGrid<>();
        grid.addHierarchyColumn(String::toString);
        ObjectOutputStream out = new ObjectOutputStream(new ByteArrayOutputStream());
        out.writeObject(grid);
        ....

This will result in an exception:
java.io.NotSerializableException: com.vaadin.flow.component.treegrid.TreeGrid$$Lambda$414/840109665
...

**Comment by Haprog** [comment]
This fix has been included in vaadin-grid-flow [4.1.1](https://github.com/vaadin/vaadin-grid-flow/releases/tag/4.1.1)
