### ISSUE TITLE
Filtering example in GridDemo should use setFilter instead of addFilter

### ISSUE THREAD

**Issue by mas4ivv** [vaadin/vaadin-grid-flow#842]
I just came across your filtering example in GridDemo.java and noticed that you are calling dataProvider.addFilter on every value change of the filter input. All filters do the same, so the result is correct, but the number of filters is growing with every change of the filter input. I unfortunately copied your example and learned this the hard way ;-)
Using setFilter should be the correct way in this example.

**Comment by mas4ivv** [comment]
OK, I just realized that setFilter only works if there is only one filtered column. So the correct solution should be to call addFilter only once for every column and call dataProvider.refreshAll on every ValueChange event.

**Comment by web-padawan** [comment]
Fixed by #1076
