### ISSUE TITLE
Scrolling is not possible if the first column is frozen and joined with others

### ISSUE THREAD

**Issue by anasmi** [vaadin/vaadin-grid-flow#846]
**Version**: 14.0.15 and 14.1.2

**Description**: Joining all columns and setting the first one to be frozen disables scrolling
**Expected behavior**: Scrolling in a grid is still possible 
**Code to reproduce**:
```
@Route("")
public class MainView extends VerticalLayout {

    public MainView() {
        add(createTestGrid());
    }

    private Grid<Person> createTestGrid() {
        Grid<Person> grid = new Grid<>(Person.class);
        grid.setColumns("id", "firstName", "middleName", "lastName");
        grid.setItems(persons());
        grid.setWidthFull();
        grid.setHeightByRows(true);
        grid.getColumns().forEach(c -> c.setAutoWidth(true));
        grid.setWidth("350px"); // To make it horizontally scrollable
        HeaderRow h = grid.prependHeaderRow();
        h.join(grid.getColumnByKey("id"),
                grid.getColumnByKey("firstName"),
                grid.getColumnByKey("middleName"),
                grid.getColumnByKey("lastName")).setText("Hello");
        grid.getColumnByKey("id").setFrozen(true); // Freeze the first column
        return grid;
    }

    private static List<Person> persons() {
        List<Person> list = new ArrayList<>();
        for(int i = 1; i <= 12; i++) {
            list.add(new Person(i, "First Name " + i, "Middle Name " + i, "Last Name " + i));
        }
        return list;
    }

    public static class Person {

        private final int id;
        private String firstName, middleName, lastName;

        public Person(int id, String firstName, String middleName, String lastName) {
            this.id = id;
            this.firstName = firstName;
            this.middleName = middleName;
            this.lastName = lastName;
        }

        public int getId() {
            return id;
        }

        public String getFirstName() {
            return firstName;
        }

        public String getMiddleName() {
            return middleName;
        }

        public String getLastName() {
            return lastName;
        }
    }
}

```

**Comment by tomivirkki** [comment]
This works as expected. If you freeze one column in a group, the whole group needs to be effectively frozen as well, and that's what's happening in this case.

Not sure how the suggested behavior would be doable UX-wise. What should the parent header cell ("Hello" in the example above) do when the grid is scrolled horizontally?
- Stay put above the frozen column but scroll elsewhere (splitting an element like this isn't technically doable). The outcome would be close to having the frozen cell in its own parent group, which can be done already.
- Fully scroll along the rest of the cells? This would detach the column from its parent group. It might visually end up below some other group if scrolled enough.

Note that the grid is still _vertically_ scrollable even in this case (where every column in the viewport is frozen)

**Comment by syampillai** [comment]
Ok.
The workaround I used in my application is to put the "Hello" in the merged header that doesn't contain the frozen column.
