### ISSUE TITLE
regression: grid.deselectAll raises an error in client when there is a templatized column

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-grid-flow#85]
Running the following code, client-side shows the error `(ReferenceError) : There is no a StateNode for the given argument.` when deselecting all by clicking on the button.

Note that replacing  `new ExampleTemplate()` in the renderer with `new Span("foo")` does not break.

```
public MainView() {
    Grid<Person> grd = new Grid<>(Person.class);
    grd.setDataProvider(new AbstractBackEndDataProvider<Person, Object>() {

        protected Stream<Person> fetchFromBackEnd(Query<Person, Object> query) {
            return Stream.generate(() -> {
                return new Person("Joe", 5);
            }).limit(query.getLimit());
        }

        protected int sizeInBackEnd(Query<Person, Object> query) {
            return 4;
        }
    });

    grd.addColumn(new ComponentTemplateRenderer<>(person -> {
        return new ExampleTemplate();
    }));
    
    Button btn = new Button("deselectAll");
    btn.addClickListener(e -> grd.deselectAll());
    
    add(btn);
    add(grd);
}
```

Simple maven project demonstrating the issue 
[platform16-grid-deselect.zip](https://github.com/vaadin/vaadin-grid-flow/files/1704036/platform16-grid-deselect.zip)

**Comment by manolo** [comment]
could you add the `app starter` label? I cannot

**Comment by caalador** [comment]
For some reason the deselect recreates 2 new templates and when running the beforeClientResponse one of those instances gets `null` from the `getElement()`
```
        // This has to be executed BEFORE model population to be able to know
        // which properties needs update to the server
        getStateNode().runWhenAttached(ui -> ui.getInternals().getStateTree()
                .beforeClientResponse(getStateNode(),
                        () -> ui.getPage().executeJavaScript(
                                "this.registerUpdatableModelProperties($0, $1)",
                                getElement(),
                                filterUpdatableProperties(allowedProperties))));
```

**Comment by caalador** [comment]
The problem doesn't surface if the renderer returns the same component for a rebuild.
So by having a `Map<Person, ExampleTemplate>` and `grd.addColumn(new ComponentRenderer<>(person -> hash.computeIfAbsent(person, key -> new ExampleTemplate())));` there is no exception.

The root of the problem comes from `AbstractComponentDataGenerator::refreshData` where if we have a rendered component for the item we create a new component and then if the node id of the new component doesn't match the old component node id we detach the old component and register a renderedComponent on the new created component.

**Comment by Legioth** [comment]
Please note that using something like `Map<Person, ExampleTemplate>` would instead cause memory to leak unless there also some code that explicitly removes components from that map.

**Comment by caalador** [comment]
That it would and lots. Also I'm not proposing that as a fix just giving out information as I find it on what the problem is.

**Comment by caalador** [comment]
vaadin/flow#3572 fixes this issue in cases where the ExampleTemplate implements an equals that bases on the Person (and datat) used to create the template component.
