### ISSUE TITLE
recalculateColumnWidth() does not work within ExpandListener

### ISSUE THREAD

**Issue by enver-haase** [vaadin/vaadin-grid-flow#855]
When expanding a node with a subtree, the expand listener is called before the client-side
is finished with expanding.
If you call recalculateWidth() within the expand listener code, then it does not have an effect for us.

However, if you create a button and a click listener and put the recalculateWidth() call there, it works fine -- the obvious difference is that the call is executed *after* the expansion is done in the browser.

**Comment by tomivirkki** [comment]
Solution proposal:
In `<vaadin-grid>` (Web Component), the invocation of `recalculateColumnWidths()` should get its execution deferred until there are no pending requests left (`grid._cache.isLoading() === false`). The condition can be checked in `__setInitialColumnWidths` which gets invoked whenever a request finishes.
