### ISSUE TITLE
Setting grid page size when binding using `@Id`

### ISSUE THREAD

**Issue by caalador** [vaadin/vaadin-grid-flow#87]
When having grid in a template and binding it using `@Id` in a `PolymerTemplate` I would like to be able to set the PageSize.

Right now this is not possible at all as setting the `page-size` attribute on the client will be overridden by the server set `pageSize` and the method `setPageSize` is private.

**Workaround:**
The only viable way to come past this is to copy the function of setPageSize an use the element api e.g.
```
        grid.getElement().setProperty("pageSize", 10.0);
        grid.getElement().setProperty("size", 0.0D);
        grid.getDataCommunicator().setRequestedRange(0, 10);
```

**Comment by pleku** [comment]
We could use a workaround for enabling the setter, as described in https://github.com/vaadin/vaadin-grid/issues/1200, but it might make sense to just wait for the proper fix to happen.

**Comment by samiheikki** [comment]
Added PR to vaadin-grid to fix the issue: https://github.com/vaadin/vaadin-grid/pull/1394

**Comment by web-padawan** [comment]
The PR linked above is merged so I assume this should be fixed now. Closing.
