### ISSUE TITLE
Drop on Grid not working

### ISSUE THREAD

**Issue by martin-petzold** [vaadin/vaadin-grid-flow#876]
I want to drag an item from one grid to another grid. It worked in earlier versions. However, with 14.1.16 and 14.1.17 it does not work. The GridDropEvent is not fired. Also, it does not show any blue frame around the grid. DragStart and DragEnd events from the source grid are fired.

```
private class MyGrid extends Grid<MyType> {
	
	public MyGrid() {
		this.setDataProvider(...);
		
		this.setRowsDraggable(true);
		this.setSelectionMode(SelectionMode.NONE);
		this.setDropMode(GridDropMode.BETWEEN);
		
		this.addDropListener(event -> {
			// does not fire!
		}
	}
}
```

**Comment by pleku** [comment]
Hi @martin-petzold, I just tested with with the latest 14.1.17 versions and with the snapshots and everything was working properly. This is the code I used:

```java
@Route("dnd")
public class DnDTestView extends VerticalLayout {

    public DnDTestView() {
        Grid<String> grid1 = new Grid<>();
        Grid<String> grid2 = new Grid<>();

        grid1.setItems("Foo", "Bar", "Baz");
        grid1.addColumn(string -> string).setHeader("Column 1");
        grid1.setRowsDraggable(true);

        add(grid1, grid2);

        grid2.setSelectionMode(SelectionMode.NONE);
        grid2.setDropMode(GridDropMode.BETWEEN);    
        grid2.addColumn(string -> string).setHeader("Column 1");
        grid2.setItems("Foo", "Bar", "Baz");
        
        grid2.addDropListener(event -> Notification.show("Dropped to :" + event.getDropTargetItem().orElse("NONE")));
    }
}
```

Can you please provide more information about how to reproduce this ?

**Comment by martin-petzold** [comment]
Does not work if you remove "grid2.setItems("Foo", "Bar", "Baz");". Cannot drop on empty grid.

**Comment by martin-petzold** [comment]
Same problem for "grid2.setItems(new LinkedList<String>());"

**Comment by tomivirkki** [comment]
Just tested with the above code and with `grid2.setItems("Foo", "Bar", "Baz")` commented out. Tried with both 14.1.16 and 14.1.17 (running in the recording below) and it seems to work as expected:
![Kapture 2020-02-11 at 12 25 49](https://user-images.githubusercontent.com/1222264/74228759-c6764a80-4cc9-11ea-9d5d-9e9e3f552bdd.gif)

Can you create a minimal example project where the issue can be reproduced?

**Comment by martin-petzold** [comment]
I'm using Google Chrome Version 63.0.3239.132

**Comment by martin-petzold** [comment]
I am using exactly your example with both grids added to a HorizontalLayout.

**Comment by martin-petzold** [comment]
Also not working with Google Chrome 79.0.3945.130

**Comment by martin-petzold** [comment]
Sorry, caused by me. I had a z-index set on the table and tbody of the grid. I had to use this in order to make tooltips show.
