### ISSUE TITLE
Restore Grid setClassNameGenerator demos

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-grid-flow#878]
The demo was removed in #472 where old demos were moved to integration tests:

https://github.com/vaadin/vaadin-grid-flow/blob/127257f4bd1a4b9b5ccea71c989ff059d40480bd/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridView.java#L1620

This demo and any other missing demos should be restored.

**Comment by web-padawan** [comment]
Note, the [current demo](https://github.com/vaadin/vaadin-grid-flow/blob/48027ca90ce5741266f5849b42c5baee8ed6baf7/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridView.java#L1620-L1672) suggests to use `dom-module`. We should consider demonstrating `@CssImport` instead (not available in Bower compatibility mode though).

**Comment by anasmi** [comment]
@hongduc-phan I have created a  pull request already. So it's in review already :)
