### ISSUE TITLE
TemplateRenderer does not render data-attribute without $

### ISSUE THREAD

**Issue by masbaehr** [vaadin/vaadin-grid-flow#910]
It seems hat not only style and class need the $ but also data attributes. 

I had to use this way for rendering a custom tooltip

data-tippy-content$='{{item.myTooltip}}'

**Comment by tomivirkki** [comment]
This is the expected behavior. If you want the element to have an attribute, attribute binding syntax (`$=`) should be used. Some properties reflect as an attribute automatically, but that's not the default behavior with Polymer or properties in general
