### ISSUE TITLE
Rework the example "Using text fields for filtering items"

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/vaadin-grid-flow#921]
Currently the "Using text fields for filtering items" demo works by calling `dataProvider.addFilter()` every time a text field is changed. This isn't a great way of doing things, as `addFilter` keeps appending filters to the DataProvider. Instead, there could be a shared data object that gets updated whenever one of the TextFields changes and the filter predicate would check the properties (name, age, ...) of the data object. That way you can use `setFilter` instead of `addFilter` and have slightly less accumulating overhead.

**Comment by web-padawan** [comment]
Fixed by #1076
