### ISSUE TITLE
A grid with many invisible columns is veeeeery slow

### ISSUE THREAD

**Issue by mvysny** [vaadin/vaadin-grid-flow#930]
Vaadin 14.1.23; Firefox 74.0

I have a Grid with potentially lots of columns. The Grid usually shows up to 10 columns, but the users have a possibility to open a column selector and show an additional column from the list of 96 columns.

The problem is that Grid with 10 columns in total is fast; a Grid with 10 visible columns and 97 columns in total is very slow: it takes roughly 10 seconds to display on Firefox 74.0, and the scrolling is slow as well. I'm attaching a screenshot from a very quick profiling session. I'll attach an example app as well.

![Screenshot from 2020-04-07 13-44-31](https://user-images.githubusercontent.com/254091/78660561-f6128f00-78d5-11ea-9228-4bf14fff2af6.png)

**Comment by mvysny** [comment]
[skeleton-starter-flow.zip](https://github.com/vaadin/vaadin-grid-flow/files/4443692/skeleton-starter-flow.zip)

```
@Route("")
@PWA(name = "Project Base for Vaadin", shortName = "Project Base")
@CssImport("./styles/shared-styles.css")
@CssImport(value = "./styles/vaadin-text-field-styles.css", themeFor = "vaadin-text-field")
public class MainView extends VerticalLayout {

    public MainView() {
        setSizeFull();

        final Grid<Integer> grid = new Grid<>();
        for (int i = 0; i < 99; i++) {
            final int columnIndex = i;
            grid.addColumn(new ValueProvider<Integer, String>() {
                @Override
                public String apply(Integer integer) {
                    return (integer * 100 + columnIndex) + "";
                }
            }).setHeader(i + "").setVisible(i < 5);
        }

        grid.setItems(IntStream.range(0, 1000).boxed());
        grid.setSizeFull();

        add(grid);
    }
}
```

**Comment by mvysny** [comment]
Related issue: https://github.com/vaadin/vaadin-grid/issues/1676

**Comment by rolfsmeds** [comment]
This is due to hidden columns still being rendered into the DOM, despite being visually hidden. There is a separate issue about this here https://github.com/vaadin/vaadin-grid/pull/1689, the fix for which is released in V14.3.

**Comment by jcgueriaud1** [comment]
It's much better in Vaadin 16. Tested with FF77 and it doesn't take 1 second.

I didn't test it in Vaadin 14.3

**Comment by tomivirkki** [comment]
Closing as per above comments (fixed by https://github.com/vaadin/vaadin-grid/pull/1689)
