### ISSUE TITLE
GridContextMenu.GridContextMenuOpenedEvent broken (no columnId)

### ISSUE THREAD

**Issue by flefebure** [vaadin/vaadin-grid-flow#971]
Hi,
I think there is some regression on the GridContextMenu.GridContextMenuOpenedEvent event.
It doesn't receive the columnId that allows to identify the column from where the context-menu has been opened.

```
public static class GridContextMenuOpenedEvent<T>
            extends OpenedChangeEvent<GridContextMenu<T>> {
        private final Grid<T> grid;
        private final transient Optional<T> item;
        private final transient Optional<String> columnId;
```

Waiting for some correction, this is my workaround to reenable the feature :
1/ First patch gridConnector.js
~~const colId = eventContext.column && eventContext.column.id;~~

```
        const contextMenuListener = function(e) {
        const eventContext = grid.getEventContext(e);
        const key = eventContext.item && eventContext.item.key;
        const colId = eventContext.column && eventContext.column._flowId;
        grid.$server.updateContextMenuTargetItem(key, colId);
      };
```
2/ make getColumnByInternalId public

```
package com.vaadin.flow.component.grid;
import com.vaadin.flow.component.dependency.JavaScript;
@JavaScript("frontend://gridConnectorPatched.js")
public class CustomGrid extends Grid {
    public CustomGrid(Class beanType) {
        super(beanType);
    }

    @Override
    public Column getColumnByInternalId(String internalId) {
        return super.getColumnByInternalId(internalId);
    }
}
```
GridContextMenuOpenedEvent should have directly a "column" property available, as the ItemClickEvent

**Comment by pekam** [comment]
It seems that `getColumnId` returns the `id` attribute of the `<vaadin-grid-column>` element. So it probably works as originally designed. So you need to first set the ids with `Column::setId` to get something out of the getter.

This is not at all obvious after reading the JavaDocs, so it should be clarified.

> GridContextMenuOpenedEvent should have directly a "column" property available, as the ItemClickEvent

I agree. This kind of `getColumnId` API should never have been added, but instead `getColumn` to get directly the reference to the column itself.

**Comment by flefebure** [comment]
Hi Pekka,
I may be wrong but I don't see any trace of this `Column::setId` setter, no more getter for "id".
Only a getInternalId() getter. But this columnInternalId property isn't available on the client side on column.id, but on column._flowId.

**Comment by pekam** [comment]
The methods `getId` and `setId` are inherited from the `Component` class. It's the HTML `id` attribute that can be set on any HTML element.

The internal id / `_flowId` is another concept, which is an implementation detail of grid and columns. They are intentionally not made publicly available.

**Comment by flefebure** [comment]
Grid.Column isn't a Component..
I've updated a "bug demo project" that i've done for https://github.com/vaadin/vaadin-grid-flow/issues/957#issuecomment-624606175

See https://github.com/flefebure/vaadin-test-grid/blob/60f75e70008df460bc42c93b5b28f50b74d4c8e0/src/main/java/com/test/TestGridRoute.java#L105 
May be you should show how to make this line work without weird trick ?

**Comment by pekam** [comment]
> Grid.Column isn't a Component..

Yes it is, as you can see [here](https://github.com/vaadin/vaadin-grid-flow/blob/9781c92ae646550433d906ffcbd3f7c8a71d6965/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractColumn.java#L38). It's the Java counterpart of the `<vaadin-grid-column>` web component.

> May be you should show how to make this line work without weird trick ?

Set ids to your columns with `setId`.

**Comment by flefebure** [comment]
~~Grid.Column isn't a Component..~~
Sorry for my mistake.. Have a good day
