### ISSUE TITLE
Demo: ArrayIndexOutOfBoundsException on "Custom Drag Data" demo

### ISSUE THREAD

**Issue by Haprog** [vaadin/vaadin-grid-flow#974]
### Description
Selecting a piece of text somewhere on the demo page and dragging it onto the grid in **Custom Drag Data** demo causes `ArrayIndexOutOfBoundsException`. This also happens if you drag an item from some of the other demos to this demo (at least when dragging an item from **Drag and Drop Filters** demo)

This causes errors to show up in our `#vaadincom-exceptions` Slack channel.

### Expected outcome
No exceptions should be thrown, no matter what you drag onto the grid (text, files, whatever).

### Actual outcome
An `ArrayIndexOutOfBoundsException` is thrown.

### Live Demo
https://vaadin.com/components/vaadin-grid/java-examples/drag-and-drop

### Steps to reproduce
1. Navigate to the **Custom Drag Data** demo at https://vaadin.com/components/vaadin-grid/java-examples/drag-and-drop
2. Select a piece of text for example from the source code block
3. Drag and drop the selected text onto the grid.

**Comment by web-padawan** [comment]
Fixes by #983 which was merged to `4.2` branch.
