### ISSUE TITLE
Demo: Grid filtering example not working as intended

### ISSUE THREAD

**Issue by tdq** [vaadin/vaadin-grid-flow#979]
Go to https://vaadin.com/components/vaadin-grid/java-examples/filtering and scroll down to "Using data type specific filtering"
The filter for "marital status" works on an attribute that isn't shown in the table. Also both options lead to an empty table.

![image1](https://user-images.githubusercontent.com/1551571/82016238-41644e00-9689-11ea-99c8-46cd3e3400de.png)

The birthdate attributes are not set thus filtering won't work either.

![image2](https://user-images.githubusercontent.com/1551571/82016262-517c2d80-9689-11ea-8bed-49e1a23c7aa6.png)

**Comment by web-padawan** [comment]
Fixed by #980 which was merged to `4.2` branch.
