### ISSUE TITLE
Grid with multiselect inside Dialog has ellipsis in selection column

### ISSUE THREAD

**Issue by TatuLund** [vaadin/vaadin-grid-flow#991]
There is a regression in Vaadin 14.2. Grid with multiselect inside Dialog has ellipsis in selection column

![image](https://user-images.githubusercontent.com/14309836/82789021-3f14a780-9e72-11ea-8e2c-5ab6d0653dee.png)

This did not happen in 14.0.x

Code to reproduce

```
        Button gridTest = new Button("Grid");
        gridTest.addClickListener(buttonClickEvent -> {
        	Dialog dialog = new Dialog();
        	Grid<Object> grid = new Grid<>();
        	grid.addColumn(x -> "aaaaaaaaaaaaa").setHeader("AAA");
        	grid.addColumn(x -> "bbbbbbbbbbbbb").setHeader("BBB");
        	grid.addColumn(x -> "ccccccccccccc").setHeader("CCC");
        	grid.setItems(IntStream.range(0, 100).mapToObj(i -> i));
        	grid.setSelectionMode(Grid.SelectionMode.MULTI);
        	grid.setSizeFull();
        	dialog.setWidth("1000px");
        	dialog.setHeight("500px");
        	dialog.add(grid);
        	dialog.open();
        });
        add(gridTest);
```

**Comment by web-padawan** [comment]
Probably related to https://github.com/vaadin/vaadin-grid/issues/1723 although that is reported for 14.1

**Comment by TatuLund** [comment]
@web-padawan Yes, looks the same. I made a correction, my contact upgraded from 14.0.x not 14.1.x.

**Comment by alvarezguille** [comment]
Versions and description are consistent with https://github.com/vaadin/vaadin-grid/issues/1723, closing as duplicate
