### ISSUE TITLE
No data refresh if calling setItems a second time

### ISSUE THREAD

**Issue by Lars-jnk** [vaadin/vaadin-grid-flow#994]
- add data to grid
- change data
- setting new data to grid

-> it didn't show the updated data
     only if a node has no childs anymore, it removes the chevron

if you open a node, you can see the updated data

tested with vaadin 15.0.6

**Comment by Lars-jnk** [comment]
Ok, it seem this appears only if the new data array has also a new element.

**Comment by tomivirkki** [comment]
Hi, can you provide a code example on how to make the issue happen

**Comment by Lars-jnk** [comment]
```
class DemoClass {
    public String name;

    public List<DemoClass> childs = new ArrayList<>();

    public DemoClass(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public List<DemoClass> getChilds() {
        return childs;
    }
}


public class DemoView extends VerticalLayout {
    public DemoView() {
        List<DemoClass> list = new ArrayList<>();
        list.add(new DemoClass("eins"));
        DemoClass dc = new DemoClass("zwei");
        dc.childs.add(new DemoClass("child"));
        list.add(dc);
        list.add(new DemoClass("drei"));

        TreeGrid<DemoClass> grid = new TreeGrid<>();
        grid.setItems(list, DemoClass::getChilds);
        grid.addHierarchyColumn(DemoClass::getName).setHeader("Name");

        Button btn = new Button("refresh Grid", e -> {
            list.add(new DemoClass("vier"));
            grid.setItems(list, DemoClass::getChilds);
        });
        add(btn);
        add(grid);
    }
}
```

**Comment by tomivirkki** [comment]
Would adding `grid.getDataProvider().refreshAll();` work for you? If you don't want to assign a new data provider (setItems) in between, you could also use:
```
grid.getTreeData().addRootItems(new DemoClass("vier"));
grid.getDataProvider().refreshAll();
```

**Comment by Lars-jnk** [comment]
`grid.getDataProvider().refreshAll();` works fine. Thank you. I wasn't aware that I have to use this method, because I didn't use any data provider. Maybee a `refreshAll()` method on `grid` would be nice.

This was only an example. In real I add the whole data with many changes.

Thanks for your help.
