### ISSUE TITLE
[Grid] ItemDoubleClickEvent listener on row of grid not working on mobile mode

### ISSUE THREAD

**Issue by letrthang** [vaadin/vaadin-grid-flow#998]
Vaadin 14.2.0.

double-click listener of **ItemDoubleClickEvent** on row of grid not working on browser mobile mode (F12 on Chrome, Edge) . What we do that when user click on a row of grid, we will open a dialog.

Tested in some phones as Samsung with chrome it works, but in iPhone 11 (chrome) not working.

In normal browser mode (chrome, MS edge), it always works fine.

**Comment by web-padawan** [comment]
There is a known issue related to `dblclick` browser event on iOS.
We workarounded that in GridPro using a [custom code](https://github.com/vaadin/vaadin-grid-pro/blob/100eed208c8606158c7f6e8b97807459eb7b70af/src/vaadin-grid-pro-inline-editing-mixin.html#L108-L135).

**Comment by tomivirkki** [comment]
It's [documented](https://github.com/vaadin/vaadin-grid-flow/blob/master/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java#L3259-L3261) in the Grid that the feature doesn't work on Mobile. Closing as a wontfix.
